### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by pradeep-bose** [intel/ipmctl#10]
$cmake -DRELEASE=ON -DCMAKE_INSTALL_PREFIX=/ ..
CMake Error: File /home/****/****/ipmctl/DcpmemPkg/driver/Doxyfile_nvm_dimm_config_protocol.in does not exist.
CMake Error at CMakeLists.txt:557 (configure_file):

At 557 line number the doxygen is unable to generate the documentation , so it fails. 

Doxyfile_nvm_dimm_config_protocol.in is not comitted part of the repository , please add the corresponding file

**Comment by pradeep-bose** [comment]
duplicate of https://github.com/intel/ipmctl/issues/2 , please merge to master

**Comment by juston-li** [comment]
The fix is still going through internal validation, will leave this issue open until it merges into master.
