### ISSUE TITLE
[README.md] Typo: "availible" should be "available"

### ISSUE THREAD

**Issue by sscargal** [intel/ipmctl#100]
In README.md the typo of "availible" appears in two places.  This should be corrected to "available".  It is correctly spelled elsewhere within README.md.  See:

`
ipmctl is availible on Fedora.
`
and
`
libsafec is availible on Fedora.
`

**Comment by kellycouch** [comment]
Thanks. Will fix.

**Comment by StevenPontsler** [comment]
README.md updated.
