### ISSUE TITLE
ipmctl v02.00.00.3535 doesn't work with AEPs

### ISSUE THREAD

**Issue by LouisLaborde** [intel/ipmctl#108]
On HPE System with AEPs devices running WS2019, ipmctl v02.00.00.3535 fails as follows:

   ipmctl show -dimm
   No DIMMs in the system.

Ipmctl v01.00.00.3469 works fine on same machine.

Isn't ipmctl v02.x.x.x supposed to be backward compatible with AEPs?

**Comment by kellycouch** [comment]
Yes. AEP support is expected. We'll investigate.

**Comment by LouisLaborde** [comment]
Debugged issue:
ipmctl v02.x.x.x now seems to require presence of ACPI PMTT table on machine.

Since it isn't a required table, this is a bug in function ParseAcpiTables() in file DcpmPkg\driver\Protocol\Driver\NvmDimmConfig.c

Excerpt from ipmctl debug verbose spew:

NVM_DBG_LOGGER NVDIMM-VERB:Entering NvmDimmDriver.c::NvmDimmDriverDriverBindingStart()
NVM_DBG_LOGGER NVDIMM-VERB:Entering NvmStatus.c::InitErrorAndWarningNvmStatusCodes()
NVM_DBG_LOGGER NVDIMM-VERB:Exiting NvmStatus.c::InitErrorAndWarningNvmStatusCodes()
NVM_DBG_LOGGER NVDIMM-WARN:os_efi_api.c::initAcpiTables:208: Failed to get the PMTT table.
NVM_DBG_LOGGER NVDIMM-VERB:Entering NvmDimmConfig.c::ParseAcpiTables()
NVM_DBG_LOGGER NVDIMM-VERB:Exiting NvmDimmConfig.c::ParseAcpiTables(): 0x2
NVM_DBG_LOGGER NVDIMM-WARN:os_efi_api.c::initAcpiTables:242: Failed to parse NFIT or PCAT or PMTT table.
NVM_DBG_LOGGER NVDIMM-WARN:NvmDimmDriver.c::NvmDimmDriverDriverBindingStart:1364: Failed to initialize the ACPI tables, error = 0xe.
NVM_DBG_LOGGER NVDIMM-VERB:Entering NvmDimmConfig.c::FillDimmList()
NVM_DBG_LOGGER NVDIMM-VERB:Entering Dimm.c::InitializeDimmInventory()
NVM_DBG_LOGGER NVDIMM-DBG:Dimm.c::InitializeDimmInventory:1296: Improperly initialized data
NVM_DBG_LOGGER NVDIMM-WARN:NvmDimmConfig.c::FillDimmList:8684: Initialization of one or more Dimms failed.
NVM_DBG_LOGGER NVDIMM-DBG:NvmDimmConfig.c::FillDimmList:8719: Found 0 DCPMMs
NVM_DBG_LOGGER NVDIMM-VERB:Exiting NvmDimmConfig.c::FillDimmList(): 0x2
NVM_DBG_LOGGER NVDIMM-WARN:NvmDimmDriver.c::NvmDimmDriverDriverBindingStart:1381: Failed to initialize Dimms, error = 0x2.
NVM_DBG_LOGGER NVDIMM-DBG:NvmDimmDriver.c::NvmDimmDriverDriverBindingStart:1449: Exiting DriverBindingStart, error = 0x2.
NVM_DBG_LOGGER NVDIMM-VERB:Exiting NvmDimmDriver.c::NvmDimmDriverDriverBindingStart(): 0x2

**Comment by kellycouch** [comment]
Quick note of clarification. 2.x is currently considered alpha stage and is not recommended for production environment. This note has been added to front page as well.
