### ISSUE TITLE
build failed on sles12.3, leap42.3

### ISSUE THREAD

**Issue by brianjmurrell** [intel/ipmctl#116]
Looks like the SUSE builds on SLES 12.3 and Leap 42.3 are failing due to:

```
[   60s] a2x: ERROR: "xmllint" --nonet --noout --valid "/home/abuild/rpmbuild/BUILD/ipmctl-01.00.00.3467/output/release/manpage/ipmctl-show-device.xml" returned non-zero exit status 4
```

[Full log](https://build.opensuse.org/public/build/home:jhli/SLE_12_SP3/x86_64/ipmctl/_log).

Any chance to fix easily enough and get new builds working for those two platforms?

**Comment by kellycouch** [comment]
Thanks for the report. We'll try to get fixed shortly.

**Comment by sscargal** [comment]
The minimum OS requirement for Intel Optane DC Persistent Memory is SLES 12sp4.  See the [OS Support Matrix](https://www.intel.com/content/www/us/en/support/articles/000032860/memory-and-storage/data-center-persistent-memory.html?productId=190349&localeCode=us_en).  If the compiler issue occurs on a supported OS, then it definitely needs to be fixed, but I wouldn't spend cycles fixing ipmctl on an unsupported OS.

**Comment by StevenPontsler** [comment]
The testing branch already had changes which I expect would enable it to be build on sles 12.3 and leap42.3. Those changes have been ported to v01.00.00.3479.  I tried them on sles 12.3 and build completed successfully.

**Comment by kellycouch** [comment]
@brianjmurrell - please give 3479 a try and we'll close if this is resolved.

**Comment by kellycouch** [comment]
@brianjmurrell - Any update?

**Comment by brianjmurrell** [comment]
@kellycouch I suppose this work is good news for other users of SLES 12.3/Leap 42.3 users, but our particular interest in those two distros has expired as they have been retired in our environment.
