### ISSUE TITLE
Decode System Timestamp from UNIX epoch into human-readable format

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#12]
In ipmctl show -dimm -error Media and -error Thermal, it would be helpful to decode the timestamp (which is in UNIX epoch format) into a human-readable timestamp.

```
Media Error occurred on Dimm (0x1001):
System Timestamp : 1531324416
DPA : 2097136
PDA : 0
Range : 6
Error Type : 4
```

The linux date command does that conversion to UTC or local time.  For the above timestamp, it calculates:
```
$ date --date @1531324416 -u
Wed Jul 11 15:53:36 UTC 2018
$ date --date @1531324416
Wed Jul 11 10:53:36 CDT 2018
```

**Comment by juston-li** [comment]
Thanks, this was in my backlog and I forgot about it.
New output:

Media Error occurred on DIMM (0x0001):
System Timestamp : Tue Jun 19 20:31:11 UTC 2018
             DPA : 0x00020000
             PDA : 0x00000003
           Range : 4B
      Error Type : 4 - Locked/Illegal Access
     Error Flags : DPA Valid
Transaction Type : 11 - CSR Write
 Sequence Number : 242

**Comment by juston-li** [comment]
Fix is in 09aff7254cc91f901603cfd7e3264eb7053a81fe

**Comment by RobertCElliott** [comment]
There is no space after "Timestamp :" like in the other rows

```
Media Error occurred on DIMM (0x1011):
System Timestamp :Thu Jun 21 17:23:50 UTC 2018
             DPA : 0x00014001
             PDA : 0x00000000
           Range : 64B
      Error Type : 4 - Locked/Illegal Access
     Error Flags : DPA Valid
Transaction Type : 13 - Unavailable
 Sequence Number : 39
```

**Comment by juston-li** [comment]
derp... good eye, will fix
