### ISSUE TITLE
'ipmctl help' not working for non-root user is inconvenient

### ISSUE THREAD

**Issue by llugin** [intel/ipmctl#124]
Is there a reason that 'version' is allowed for non-root user, but 'help' is not?

**Comment by kellycouch** [comment]
Can't think of a good reason for that... We'll look into it. Thanks for reporting.

**Comment by kellycouch** [comment]
Hi llugin - what version of ipmctl did you encounter this issue?

**Comment by llugin** [comment]
Hi. I'm using v01.00.00.3494

**Comment by kellycouch** [comment]
Thanks for following up. That is a defect we are unlikely to fix on v1. Please give v2 build a try to see if it is resolved. v2 is expected to move to recommended soon and can then be used in place of v1.

**Comment by StevenPontsler** [comment]
The v02.00.00.3709 tag on the testing branch has a fix for this issue.
