### ISSUE TITLE
Doc: `missing closing deliminter` in `ipmctl-show-error-log`

### ISSUE THREAD

**Issue by ahkok** [intel/ipmctl#125]
I'm trying to enable man pages for `clearlinux` and we run into this doc issue when building with `asciidoc` enabled:

```
/usr/bin/asciidoc.py --backend docbook -a "a2x-format=manpage"  --doctype manpage --attribute "mansource=ipmctl" --attribute "manmanual=ipmctl" --attribute "ipmctl_version=01.00.00.9999" --attribute "os_build=1" --attribute "manpage=1"  --out-file "/builddir/build/BUILD/ipmctl-02.00.00.3694/output/debug/manpage/ipmctl-show-error-log.tmp.xml" "/builddir/build/BUILD/ipmctl-02.00.00.3694/output/debug/manpage/ipmctl-show-error-log.tmp.txt"
asciidoc: ERROR: ipmctl-show-error-log.tmp.txt: line 103: [blockdef-example] missing closing delimiter
```

Note: we currently can not enable asciidoctor and are using asciidoc.

Ref for our own github issue: https://github.com/clearlinux/distribution/issues/1643

**Comment by ahkok** [comment]
https://asciidoctor.org/docs/user-manual/#verse

Seems trivial to fix - enclose the block in `____` lines.

**Comment by StevenPontsler** [comment]
The v02.00.00.3709 tag on the testing branch has changes to address the issue. I got a test system with asciidoc and ran the documentation through there. I corrected any errors. The documentation needs to be looked at closer for consistency -- particularly formatting though I think that is not such a problem for man pages.
