### ISSUE TITLE
ipmctl 2.0 has hardwired topology for Purley

### ISSUE THREAD

**Issue by Mark-Baker** [intel/ipmctl#129]
It appears ipmctl 2.0 still has hardwired topology for Purley. 
./DcpmPkg/driver/Utils/ProcessorAndTopologyInfo.h

 // 2 iMC and 3 channels each - purley
#define IMCS_PER_CPU_2_3                2
#define CHANNELS_PER_IMC_2_3            3
#define DIMMS_PER_MEM_CTRL_2_3          6

see ProcessorAndTopologyInfo.c for more Purley specific code

This breaks (say) creating AppDirect Interleaved sets on next generation DCPMM platforms

rpmbuild.sh contains a flag for Whitley , but there are no code changes created with this flag.

**Comment by kellycouch** [comment]
Thanks for the report. We'll look into it.
