### ISSUE TITLE
Unable to create namespace using ipmctl 

### ISSUE THREAD

**Issue by pradeep-bose** [intel/ipmctl#13]
The goal has been set using the ipmctl and is successful, after that

$ipmctl create -namespace -region 0 
get the below error , from the master branch latest code as below , 
on a fedora 28 , with kernel 4.17 , with pmdk and all the pre-requisite software installed

Syntax Error: Invalid or unexpected token -namespace.
Did you mean:
create [-help|-h] [-force|-f] [-units|-u (B|MB|MiB|GB|GiB|TB|TiB)] [-output|-o (text|nvmxml)] [-dimm (DimmIDs)] -goal [-socket (SocketIDs)] [MemoryMode=(0|%)] [PersistentMemoryType=(AppDirect|AppDirectNotInterleaved)] [Reserved=(0|%)] [Config=(MM|AD|MM+AD)] [NamespaceLabelVersion=(1.1|1.2)]

**Comment by juston-li** [comment]
ipmctl does not manage namespaces anymore, in favor of using OS specific tools.
For linux that would be ndctl: https://github.com/pmem/ndctl

**Comment by pradeep-bose** [comment]
Thanks for the info
