### ISSUE TITLE
Unable to unitilize libimpctl after uninitializing it

### ISSUE THREAD

**Issue by iwankgb** [intel/ipmctl#133]
Summary:
It seems to be impossible to execute following calls: `nvm_init()`, `nvm_uninit()`, `nvm_init()` and `nvm_get_nvm_capacities()`. See https://github.com/google/cadvisor/issues/2457 for detailed description.

I believe that it's perfectly valid requirement to execute `nvm_init()` and `nvm_unit()` only once during process life but such limitation should be clearly documented. At the moment `libipmctl` lacks such information.

Host details:
```
[root@localhost ~]# ipmctl version
Intel(R) Optane(TM) DC Persistent Memory Command Line Interface Version 02.00.00.3719
[root@localhost ~]# uname -r
3.10.0-1062.12.1.el7.x86_64
[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```

**Comment by kellycouch** [comment]
Thanks for the report. We'll investigate.

**Comment by kellycouch** [comment]
Please review fix and provide feedback.
