### ISSUE TITLE
Create namespace device on windows10

### ISSUE THREAD

**Issue by MagicVin** [intel/ipmctl#134]
Hi guys, 
I know how to create namespace & create the filesystem(ext4) with AEP on Linux.
But I have a question for creating the namespace device & filesystem(NTFS) under windows10 because I can't find the ndctl.exe tool from the BKC.

Do you have any suggestions?
Welcome previously!

**Comment by kellycouch** [comment]
Hi,

ndctl is a native Linux tool and not available on other Operating Systems. However, Windows has native tools as well. Please have a look at these resources:

https://docs.pmem.io/persistent-memory/getting-started-guide/creating-development-environments/windows-environments

https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-pmem

**Comment by MagicVin** [comment]
> Hi,
> 
> ndctl is a native Linux tool and not available on other Operating Systems. However, Windows has native tools as well. Please have a look at these resources:
> 
> https://docs.pmem.io/persistent-memory/getting-started-guide/creating-development-environments/windows-environments
> 
> https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-pmem

Thanks to Kellcouch, It works for me.
I can operate the pmem device to create NTFS filesystem for storing some files.

Steps of configuring AEP:
1. login the PowerShell with administrator access.
2. create AD goal by ipmctl.exe, then reboot.
3. list the physical persistent memory devices(NVDIMM)
 **Get-PmemPhysicalDevice**
4. list the physical disk(ssd/nvdimm/...)
 **Get-PhysicalDisk**
5. check PMEM disk
 **Get-PmemDisk**
6. create the region
 **Get-PmemUnusedRegion**
7. create new PMEM disk
 **Get-PmemUnusedRegion | New-PmemDisk -AtomicityType BlockTranslationTable**
8. list the physical disk
 **Get-PhysicalDisk**
9. initialize the new PMEM disk
 Get-Disk -FriendlyName Persistent* | Initialize-Disk
10. create new volume, then format them
 Get-Disk -FriendlyName Persistent* | New-Partition -UseMaximumSize -AssignDriveletter | Format-Volume -Filesystem NTFS
11. list physical disk  
 **Get-PhysicalDisk**
 **Get-Disk**


Option: 
You can configure the AEP on Linux firstly, then replace the Linux to Windows*.
