### ISSUE TITLE
libipmctl: device_fw_info.FWImageMaxSize is not populated in bytes

### ISSUE THREAD

**Issue by kjacque** [intel/ipmctl#139]
OS: CentOS 7.7.1908
Kernel: 3.10.0-1062.18.1.el7.x86_64
FW Version: 01.00.00.5127
Ipmctl version: 02.00.00.3764

`nvm_get_device_fw_image_info` is reporting back a different FWImageMaxSize than shown in the ipmctl command line tool.

In nvm_management.h, the comments for `struct device_fw_info` say that the size should be in bytes. It is actually a count of 4096-byte chunks. It looks like the value is converted to bytes for the CLI output, but not for the API: https://github.com/intel/ipmctl/blob/fbffe7316a233b845f01967533f529e96ee6411c/DcpmPkg/driver/Protocol/Driver/NvmDimmConfig.c#L1140

I'm planning to work around this in my code, but it would be good to update the comment.

**Comment by kellycouch** [comment]
Thanks for the report. We'll look into it.
