### ISSUE TITLE
When the region is in, if I shut down the server and unplug the AEP DIMMS, will it damage the server or AEP DIMMS?

### ISSUE THREAD

**Issue by HBKO** [intel/ipmctl#147]
Based on the fact that the region cannot be deleted and can only be overwrite using the ipmctl command.
When the region is in, if I shut down the server and unplug the AEP DIMMS, will it damage the server or AEP DIMMS?
how to remove AEP DIMMS without damage to the server and AEP DIMMS?

**Comment by StevenPontsler** [comment]
If the server is shutdown and powered off then carefully removing the AEP DIMMS should not damage the DIMMS' or the server's electronics. Of course working on electronics like that always has some potential risk. This would be similar to removing a DDR DIMM. The data on the DIMMS will not be available so if the server's operating system is stored on them then it will not boot.

I would strongly encourage backing up any data that you may want to retrieve before removing the DIMMS. If the configuration is not returned to the exact same state then existing region(s) may not be recovered. A new region could be created that would overwrite the existing one.

**Comment by HBKO** [comment]
Thank you very much for your answer!

**Comment by HBKO** [comment]
Thank you very much for your answer

**Comment by sscargal** [comment]
It is highly recommended to label the PMem module with the DIMM slot it was installed in. Several OEM systems (BIOS) will lock/freeze your PMem modules if you [re]install them in different slots. 

Additionally, you can move the PMem modules to another physical server so long as you disable the security first (passphrase).
