### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lidiawarnes** [intel/ipmctl#15]
I am trying to build ipmctl in Ubuntu, the CMakeError.log show the following error:

/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_44c63.dir/CheckFunctionExists.c.o  -o cmTC_44c63 -lpthreads
**/usr/bin/x86_64-linux-gnu-ld: cannot find -lpthreads**
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_44c63.dir/build.make:97: recipe for target 'cmTC_44c63' failed
make[1]: *** [cmTC_44c63] Error 1
make[1]: Leaving directory '/root/temp/ipmctl/output/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_44c63/fast' failed
make: *** [cmTC_44c63/fast] Error 2

after I have added the following library:

apt search libpthread-stubs0-dev
Sorting... Done
Full Text Search... Done
libpthread-stubs0-dev/bionic,now 0.3-4 amd64 [installed]
  pthread stubs not provided by native libc, development files

How can I fix this problem?

Thank you

**Comment by juston-li** [comment]
What Ubuntu version are you using?

Also, if you clear out the cmake cache what does the output of the initial 'cmake ..' say? It should try to look for pthreads.

**Comment by lidiawarnes** [comment]
Here is the Ubuntu version:

 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lidiawarnes** [comment]
Also, the original error was:
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_cf994.dir/build.make:97: recipe for target 'cmTC_cf994' failed
make[1]: *** [cmTC_cf994] Error 1

As mentioned above the libpthead-stubs0-dev function is loaded.

**Comment by juston-li** [comment]
Could I get the ubuntu release version too please? 'cat /etc/os-release'

I've only built ipmctl on 17.10 and 18.04. Actually did it on the fresh 18.04 install a couple days also, don't recall installing anything for pthreads.

**Comment by lidiawarnes** [comment]
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by juston-li** [comment]
Hmm I'll look into the packages I have on my system.

In the meantime, if you just want to use ipmctl on ubuntu you can find packages here: https://launchpad.net/~jhli/+archive/ubuntu/ipmctl

**Comment by juston-li** [comment]
Resolved
The CMakeError.log is quite cryptic in this case, really it was just missing the dependency for libsafec-devel
