### ISSUE TITLE
Using DCPMM as Main Memory without DRAM Cache

### ISSUE THREAD

**Issue by jieliangang** [intel/ipmctl#152]
I am referring to Section 2.3.1 of "[Basic Performance Measurements of the Intel Optane DC Persistent Memory Module](https://arxiv.org/abs/1903.05714)". 

> **MM-Optane-Uncached** In this configuration, we use uncached Optane DC as the system memory, that is, without DRAM caching Optane DC. This configuration represents a Optane DC system configuration where raw, uncached Optane DC is used as the main memory device. We include this configuration since the DRAM cache in MM-Optane- Cached obscures the raw performance of the Optane DC media — we do not expect this to be a common system configuration. To build this configuration, we configured the Optane DC PMM into App Direct mode and let the Linux kernel consider Optane DC to be DRAM. The kernel considers Optane DC to be slower memory and DRAM to be faster memory, and puts them in two separate NUMA nodes. Although it would be interesting to measure the performance when the whole system running directly on the NVMM, we cannot boot the operating system without any DRAM. Therefore, to run the tests, we configure applications to bind their memory to a NUMA node with exclusively Optane DC memory.

Instead of configuring DCPMM as Memory Mode, in which the DRAM would act as a last level cache, I would like to test with DCPMM as the main memory without the DRAM cache. 

The author of the paper 

> _"configured the Optane DC PMM into App Direct mode and let the Linux kernel consider Optane DC to be DRAM"_.
 
May I know how can the Linux kernel be configured to consider persistent memory to be DRAM?

I tried out this guide ([How To Extend Volatile System Memory (RAM) using Persistent Memory on Linux](https://stevescargall.com/2019/07/09/how-to-extend-volatile-system-memory-ram-using-persistent-memory-on-linux/)), but my Linux kernel version (4.14) is <v5.1 which is required for the guide. It seems like I couldn't enable the migrate device model daxctl support.
 
This was also raised in #120 but I wasn't able to find a solution from there. 

The machine in the paper is of Linux kernel version 4.13.0. Thus, there should be a way to configure the kernel (4.14) to consider persistent memory as DRAM. How can I configure DCPMM as main memory without the DRAM cache? Thanks!

**Comment by sscargal** [comment]
@jieliangang I confirmed with the paper authors that they used some custom code, and the feature they describe by MM-Optane-Uncached is not available in the mainline kernel. 

As you found, the DAX-KMEM feature allows us to provision PMem through the Kernel, but this requires Kernel v5.2 or later. There is a Memory Tiering feature currently in development that allows the Kernel to manage both DRAM and PMem allocations, but this won't be available for a while. 

A user-space solution can be achieved using [MemKind](http://memkind.github.io/memkind/), but this requires modifying the app to use the API. 

[Memverge ](http://memverge.com/)has a solution that can use both DRAM and PMem for volatile allocations, plus they can snapshot, clone, and restore the memory resident image. Their product targets unmodified applications but also allows ISVs to use their APIs for more control.

**Comment by StevenPontsler** [comment]
Thanks for responding @sscargal  I had no idea how to do it. Certainly ipmctl does not have a function for it.

**Comment by sheepx86** [comment]
Hi @jieliangang, I am a co-author of the paper you mentioned. At the time we were doing the experiments, the KMEM feature was not available yet. What we did was simply replace `E820_TYPE_PMEM` with `E820_TYPE_RAM` in the boot code (the locations in UEFI and BIOS boot code are different). It was mostly a hack but worked for our purposes.

I would strongly recommend you to switch to a newer kernel and use the DAX-KMEM feature now.

**Comment by jieliangang** [comment]
Thanks @sscargal and @sheepx86 for the tips and assistance!! I will switch to a newer kernel and try out the DAX-KMEM feature.

**Comment by kjfbjweerjfn** [comment]
We are trying to use the same configuration by following this [article](https://stevescargall.com/2019/07/09/how-to-extend-volatile-system-memory-ram-using-persistent-memory-on-linux/), however we notice some unusual behaviour. We run the application (mysql) on the newly created numa node 2 (using numactl). And use the Intel vtune platform profiler. As expected, the pmem starts experiencing reads and writes, but the dram still continues being used moderately, albeit less than before, as evident from the following charts. Why does this happen ? There is no other application being run. We also ran the profiler when the system was completely idle and noticed that dram throughput was much lower. 
Then we also used numastat command to verify the memory allocations and could see that the other numa nodes (i.e. dram) were mostly free. So this means the numactl command worked as intended.  
Please let us know what you think could be causing this, or is there any other way to achieve this configuration. 
```


                         Node 0          Node 1          Node 2           Total
                 --------------- --------------- --------------- ---------------
MemTotal                64047.45        64499.12        63488.00       192034.57
MemFree                 60728.69        63223.74          162.67       124115.10
MemUsed                  3318.76         1275.38        63325.33        67919.46
```
![github](https://user-images.githubusercontent.com/89146541/129923477-251939a4-921a-4c8d-99c7-c0755d82ed46.png)

**Comment by sscargal** [comment]
@kjfbjweerjfn 

> There is no other application being run.

The Kernel/OS is running and will need the DRAM for internal buffers and the Page Cache.

**Comment by StevenPontsler** [comment]
Thanks for responding @sscargal -- it looks like this is a question about an article you are hosting. Is there a better place for questions about that to be asked?

**Comment by sscargal** [comment]
There is a PMem forum ([https://groups.google.com/forum/#!forum/pmem](https://groups.google.com/forum/#!forum/pmem)) and [#pmem Slack Channel](https://join.slack.com/t/pmem-io/shared_invite/enQtNzU4MzQ2Mzk3MDQwLWQ1YThmODVmMGFkZWI0YTdhODg4ODVhODdhYjg3NmE4N2ViZGI5NTRmZTBiNDYyOGJjYTIyNmZjYzQxODcwNDg) where questions can be asked.

**Comment by kjfbjweerjfn** [comment]
> @kjfbjweerjfn
> 
> > There is no other application being run.
> 
> The Kernel/OS is running and will need the DRAM for internal buffers and the Page Cache.

Thank you for your reply. In this case, the page cache gets allocated on the numa node meant for pmem, if you look at the rows Active(file) and Inactive(file).
```

                         Node 0          Node 1          Node 2           Total
                 --------------- --------------- --------------- ---------------
MemTotal                64047.45        64499.12        63488.00       192034.57
MemFree                 60728.69        63223.74          162.67       124115.10
MemUsed                  3318.76         1275.38        63325.33        67919.46
Active                     81.68           49.91           44.39          175.99
Inactive                  648.91          498.10        63258.06        64405.07
Active(anon)               57.39           30.28           38.25          125.92
Inactive(anon)            626.93          488.92          339.12         1454.96
Active(file)               24.29           19.63            6.15           50.07
Inactive(file)             21.99            9.18        62918.94        62950.11
Unevictable                 0.00            0.00            0.00            0.00
Mlocked                     0.00            0.00            0.00            0.00
Dirty                       0.00            0.01            0.00            0.01
Writeback                   0.00            0.00            0.00            0.00
FilePages                  86.66           25.43        63300.14        63412.23
```
