### ISSUE TITLE
ipmctl.exe will create %APPDATA% folder in current folder

### ISSUE THREAD

**Issue by yechun1** [intel/ipmctl#157]
Case: ipmctl.exe will create %APPDATA% folder in current folder?
Platform: Neon City
OS: Windows Server 2019
PMem: AEP QS sample
Ipmctl: 01.00.00.3497
Reproduce steps:
1.	Open cmd in Windows OS
2.     echo %APPDATA%
        c:\Users\Administrator\AppData\Roaming
2.	Run ipmctl show -a -dimm
3.	Check if there is %APPDATA% be created in current folder
Actual: %APPDATA% folder will be created under current folder 
Expect: Do not create %APPDATA% under current folder. It should be  in c:\Users\Administrator\AppData\Roaming

Is this a issue that %APPDATA% has been created under current folder?

**Comment by yechun1** [comment]
Hi,
We have just verified that latest ipmctl 1.x version (1.2.0.5444) could still have this issue.
While latest ipmctl 2.x (02.00.00.3833.exe) have no this issue, this is no %AppData% be created by 02.00.00.3833.
Does 2.x is compatible with AEP? Would you please help to suggest that if we could use 02.00.3833 for AEP configuration?

**Comment by StevenPontsler** [comment]
Hi,

The latest release of 1.x ipmctl is 01.00.00.3515 and is available [here](https://github.com/intel/ipmctl/releases/tag/v01.00.00.3515)

I would not expect a file to be written out by the command "ipmctl show -a -dimm" and I tried it on my system I do not find any command written out. I downloaded the installer from the link in the beginning of the message for my check.

What is the file that is getting written out?

Where did you get the 1.2.0.5444 version?

The 2.0.x versions are intended to work with Gen 1 modules as well as Gen 2.

If you created a fix and submitted it we would definitely consider it.

**Comment by yechun1** [comment]
Sorry that I have typed the wrong version 1.2.0.5444 that is for fw version. The one we tested is 01.00.00.3506.
we'll test the latest one with 01.00.00.3515 again. Thanks.

**Comment by yechun1** [comment]
01.00.00.3515 still have the same behavior.
That after run "ipmctl show -dimm" there will be %APPDATA% folder and %APPDATA%/Intel/ipmctl subfolders created under current path.

![image](https://user-images.githubusercontent.com/10727041/104266165-04778200-54ca-11eb-99d7-420fef2e2c8d.png)

**Comment by yechun1** [comment]
Looks like this folder is created for event log. The the commit-https://github.com/intel/ipmctl/commit/ec64aa1cb7e created this TEMP_FILE_PATH, and the folder could be configured under  C:\Users\Administrator\AppData\Roaming\Intel\ipmctl\ipmctl.ini
`TEMP_FILE_PATH = %APPDATA%\\Intel\\ipmctl\\`

Why gen2 has no this issue because gen2 have removed event log an will not create such TEMP_FILE_PATH.
So I think this is not a bug, but temporary folder be created for capture event logs.

**Comment by yechun1** [comment]
Search from the code, I did not find any place used this TEMP_FILE_DIR. Could below code which create temp_file_path been removed? If there is no impact, I could submit a patch for it.

```
  // Check if the TEMP_FILE_DIR exists and create it if not
  if (FALSE == temp_dir_created) {
    if (FALSE == g_log_file_table[SYSTEM_LOG_AR_FILE].name_initialized) {
      efi_status = preferences_get_string_ascii(g_log_file_table[SYSTEM_LOG_AR_FILE].ini_entry_name, guid, SYSTEM_LOG_FILE_NAME_MAX_LEN, g_log_file_table[SYSTEM_LOG_AR_FILE].file_name);
      if (EFI_SUCCESS == efi_status) {
        g_log_file_table[SYSTEM_LOG_AR_FILE].name_initialized = TRUE;
      }
    }
    // Create the TMEP_FILE_DIR
    os_mkdir(g_log_file_table[SYSTEM_LOG_AR_FILE].file_name);
    temp_dir_created = TRUE;
  }

```

**Comment by yechun1** [comment]
@StevenPontsler The %APPDATA% should be replaced as real value as this is environment variables under Windows. I have reuse the code in the next section to fix the issue, would you please help review the patch: #159, thanks.

**Comment by StevenPontsler** [comment]
I 'll try to give it a more complete review next week.
