### ISSUE TITLE
Is aarch64 currently supported?

### ISSUE THREAD

**Issue by sktzwhj** [intel/ipmctl#163]
Hi all,

May I ask if aarch64 is currently supported by ipmctl? 

I tried to compile from the source and got an error saying the lack of cpuid.h file while compiling lnx_system target. I searched a bit and found no such header is provided for aarch64. 

Not sure if there are more problems as the compilation goes on.  Could anyone please let me know if there are any successful cases to deploy on aarch64?

Cheers,
Hector

**Comment by StevenPontsler** [comment]
I am not aware of anything being done on aarch64 for ipmctl. I believe aarch64 is for Arm. The ipmctl application is for configuring Intel® Optane™ Persistent Memory modules and I am unaware of any Arm products that support those devices so I doubt ipmctl would be useful.

I did find on my system that if I commented out the include directive for cpuid.h that ipmctl still built.

**Comment by sscargal** [comment]
Intel Optane Persistent Memory devices use the DDR-T protocol which is proprietary to Intel x64 CPUs. I am not aware of any other CPU architecture that supports DDR-T, hence ipmctl won't work on anything other than Intel platforms. For generic NVDIMM support, see the [ndctl ](https://github.com/pmem/ndctl) Linux utility. 

Each PMem vendor is responsible for creating utilities to support their product and work with the OEM BIOS teams to add provisioning functionality.

**Comment by sktzwhj** [comment]
Thanks for the answers.
