### ISSUE TITLE
Failure to create goal with ipmctl 2.x while legacy remained and previously configured by ipmctl 1.x

### ISSUE THREAD

**Issue by gaoethan** [intel/ipmctl#165]
Received some Apache Pass of 256G with firmware versions of **_01.02.00.5375_ and _01.02.00.5435_**, and we found that region configured didn't fit to our needs after install them into servers, currently, the ipmctl is **_2.x_** _**(Version - 02.00.00.3809)**_ in CentOS 8.3 and tried to  run
`$ ipmctl delete -pcd <config>`
then it indicates to reboot to take effect, it looks like something different from the previous region configuration after the reboot, but it also can't create goal, next to repeatedly trying to delete, create and reboot, and it always failed to create goal no matter in MM or AD mode

Finally, we uninstalled the ipmctl 2.x and installed _**ipmctl 1.x (Version - 01.00.00.3474)**_ manually with its RPM packages. then to delete the configuration and create the goal again just like before. it went well and finally created the expected goal successfully. 

So... 

- Does it mean that ipmctl 2.x can't operate the configuration created previously by ipmctl 1.x ?  
- Any other internal difference btw ipmctl 1.x and 2.x, or even related to the firmware of persistent memory ?

It's important to make it for our ongoing production with persistent memory, thanks !

**Comment by sscargal** [comment]
@gaoethan There was a bug in ipmctl v02.00.00.3809 that caused the goal to not apply after reboot. See #149. The configure issue was resolved in v02.00.00.3820 or later. You will find ipmctl-02.00.00.3833 in the package repository, so you should upgrade to the latest version of ipmctl before you provision new systems to avoid the issue. 

The `delete -pcd` command does not wipe all copies of the PCD, The only way to do wipe all PCD copies is to perform an `ndctl  sanitize-dimm` operation. See [How to Securely Erase Data on Intel® Optane™ Persistent Memory](https://software.intel.com/content/www/br/pt/develop/articles/how-to-securely-erase-data-on-intel-optane-persistent-memory.html) for more information.

**Comment by gaoethan** [comment]
Awesome !

So... Can I conclude that there is no problem by using ipmctl 2.x (after v02.00.00.3820) to manage or configure the things created with ipmctl 1.x  ?

Because I just worry about there is some mandatary dependency which leads to use two versions ipmctl respectively in the follow-up production cases with our customers.

Many thanks !

**Comment by sscargal** [comment]
> Can I conclude that there is no problem by using ipmctl 2.x (after v02.00.00.3820) to manage or configure the things created with ipmctl 1.x ?

For this particular issue, you should use v02.00.00.3820 or later. I recommend using the latest version available in the package repo. At the time of writing, it's v02.00.00.3833.

> Because I just worry about there is some mandatary dependency which leads to use two versions ipmctl respectively in the follow-up production cases with our customers.

Most users update the packages after the initial OS install to ensure they get the latest security and bug fixes. Updating the ipmctl package would be part of that process. Otherwise, you could update only the ipmctl package before provisioning the PMem. 

Alternatively, provision PMem through the BIOS or platform management (BMC, iLO, iDRAC, etc) in which case you may elect not to install ipmctl unless you want to use it for monitoring PMem.

**Comment by StevenPontsler** [comment]
The ipmctl team has received feedback that they do not want to be required to have different versions of ipmctl for different hardware generations. Thus, there is the goal to keep ipmctl backwards compatible with previous hardware generations. Backwards incompatibilities are viewed as defects.

Distro's have generally not been willing to take each release so it is best to check for the latest here or if you are working directly with Intel check with your Intel contact to get the version with the latest bug fixes.

**Comment by gaoethan** [comment]
Many thanks for your great sharing and answers ! I think, it's clear to me and here to close it.
