### ISSUE TITLE
build error with gcc11

### ISSUE THREAD

**Issue by anujm1** [intel/ipmctl#169]
| /ipmctl/03.00.00.0302-r0/git/DcpmPkg/common/PbrOs.c: In function 'PbrSerializeCtx':
| /ipmctl/03.00.00.0302-r0/git/DcpmPkg/common/PbrOs.c:137:3: error: 'os_mkdir' accessing 4096 bytes in a region of size 100 [-Werror=stringop-overflow=]
|   137 |   os_mkdir(pbr_dir);
|       |   ^~~~~~~~~~~~~~~~~
| compilation terminated due to -Wfatal-errors.
| cc1: all warnings being treated as errors

and

| /ipmctl/03.00.00.0302-r0/git/src/os/ini/ini.c: In function 'nvm_ini_dump_to_file':
| /ipmctl/03.00.00.0302-r0/git/src/os/ini/ini.c:462:7: error: 'os_mkdir' accessing 4096 bytes in a region of size 1024 [-Werror=stringop-overflow=]

**Comment by sscargal** [comment]
@anujm1 - Please provide more information about your OS and build environment. 

- What OS are you using? (Linux, Windows, other?)
- What OS/Kernel version are you using?
- What gcc version are you using?

**Comment by anujm1** [comment]
I am using Linux, kernel 5.10 with Yocto. I can't use an older compiler version. Fedora has also started using gcc 11 with Fedora 34.

**Comment by StevenPontsler** [comment]
I think I can see what the warning is about. We will take a look into it soon.
