### ISSUE TITLE
Replace AppDirect2Size with ReservedSize in -goal commands

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#17]
create -goal and show -goal include two AppDirectSize values, but only one is used; AppDirect2Size doesn't really exist.

SocketID        DimmID  MemorySize      AppDirect1Size  AppDirect2Size
0x0000          0x0001  0.0 GiB         125.0 GiB       0.0 GiB
0x0000          0x0011  0.0 GiB         125.0 GiB       0.0 GiB

**Suggestions:**
1. Delete AppDirect2Size (and drop the 1 from AppDirect1Size).

2. Since create -goal works by selecting the memory size and reserved size (implying the persistent memory size), show the Reserved size instead.

```
ipmctl create -goal PersistentMemoryType=AppDirect

The following configuration will be applied:

SocketID        DimmID  MemorySize      AppDirect1Size  AppDirect2Size
0x0000          0x0001  0.0 GiB         125.0 GiB       0.0 GiB
0x0000          0x0011  0.0 GiB         125.0 GiB       0.0 GiB
```
 ```
ipmctl create -goal Reserved=50 PersistentMemoryType=AppDirect

The following configuration will be applied:

SocketID        DimmID  MemorySize      AppDirect1Size  AppDirect2Size
0x0000          0x0001  0.0 GiB         62.0 GiB        0.0 GiB
0x0000          0x0011  0.0 GiB         62.0 GiB        0.0 GiB
```
It'd be helpful to show:
```
SocketID        DimmID  MemorySize      AppDirectSize  ReservedSize
0x0000          0x0001  0.0 GiB         62.0 GiB        63.0 GiB
0x0000          0x0011  0.0 GiB         62.0 GiB        63.0 GiB
```
ipmctl's create arguments are:
```
    create [-help|-h] [-force|-f] 
        [-units|-u (B|MB|MiB|GB|GiB|TB|TiB)]
        [-output|-o (text|nvmxml)]
        [-dimm (DimmIDs)]
        -goal
        [-socket (SocketIDs)]
        [MemoryMode=(0|%)]
        [PersistentMemoryType=(AppDirect|AppDirectNotInterleaved)]
        [Reserved=(0|%)]
        [NamespaceLabelVersion=(1.1|1.2)]
```

**Comment by juston-li** [comment]
There are certain topologies that will cause a goal with a second interleave set (AppDirect2Size). Granted they aren't common and usually not optimal.

The real problem here is that we ran out of real estate and the output is about to wrap so we can't put both fields =/

**Comment by StevenPontsler** [comment]
We are keeping input and output changes to a minimum. We will not be making the requested change.
