### ISSUE TITLE
IPMCTL version incompatible

### ISSUE THREAD

**Issue by lcoon815** [intel/ipmctl#177]
I encountered version incompatible issue. Please provide guidance on how to upgrade the IPMCTL version on my RHEL 8.4.
Below is the message wheh I typed ipmctl show -dimm in the Terminal.
"This version of ipmctl is incompatible with the UEFI platform firmware. Please upgrade to a newer version of ipmctl."

**Comment by sscargal** [comment]
@lcoon815 The ipmctl package lives in the EPEL repository. The EPEL repository has `ipmctl-02.00.00.3885`. If you initially installed ipmctl from the EPEL repo, then update the ipmctl package with:

```
$ sudo dnf update ipmctl
- or -
$ sudo yum update ipmctl 
```

If you do not have the EPEL repository enabled, how did you install ipmctl originally?

**Comment by StevenPontsler** [comment]
@icoon815 - How did you originally acquire ipmctl?

If from EPEL then sscargal has the correct directions.

I am guessing that error message is not indicating the true problem.

What version of ipmctl are you using?  `ipmctl version`
Can you run the same command with the -v option which prints out debugging information and post it here? `ipmctl show -v -dimm`

**Comment by lcoon815** [comment]
Many thanks to StevenPontsler and sscargal. The issue has been resolved.
