### ISSUE TITLE
Add a Repology.org Badge to the README.md for easy reference

### ISSUE THREAD

**Issue by sscargal** [intel/ipmctl#186]
[Repology.org](https://repology.org/project/ipmctl/versions) tracks which version of ipmctl is included with which Linux distribution. This is a nice to have feature in the README.md for quick and easy reference rather than going to pkgs.org or repology.org. An example is shown below:

![ipmctl_add_repology_to_readme](https://user-images.githubusercontent.com/37674041/157556814-a6b998a8-674e-472f-8dde-5118c72c6d5c.png)

**Comment by StevenPontsler** [comment]
That looks helpful. I'll review the pull request.
