### ISSUE TITLE
show -topology and show -dimm capacity displays

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#19]
A few nits using show -topology with different units.
```
ipmctl show -u B -topology  -dimm 0x0011
ipmctl show -u MB -topology  -dimm 0x0011
ipmctl show -u GB -topology  -dimm 0x0011
ipmctl show -u TB -topology  -dimm 0x0011
ipmctl show -u MiB -topology  -dimm 0x0011
ipmctl show -u GiB -topology  -dimm 0x0011
ipmctl show -u TiB -topology  -dimm 0x0011

DimmID  MemoryType      Capacity        PhysicalID      DeviceLocator
0x0011  DCPMEM          134955925504 B  0x0027          PROC 1 DIMM 9
0x0011  DCPMEM          134955.9 MB     0x0027          PROC 1 DIMM 9
0x0011  DCPMEM          134.9 GB        0x0027          PROC 1 DIMM 9
0x0011  DCPMEM          0.1 TB  0x0027          PROC 1 DIMM 9
0x0011  DCPMEM          128704.0 MiB    0x0027          PROC 1 DIMM 9
0x0011  DCPMEM          125.6 GiB       0x0027          PROC 1 DIMM 9
0x0011  DCPMEM          0.1 TiB 0x0027          PROC 1 DIMM 9
```

This is based off SMBIOS type 17 record, which in this case is reporting 128704 MiB, so the real values are:
```
134955925504 B
134955.925504 MB
134.955925504 GB
0.134955925504 TB
128704 MiB
125.6875 GiB
0.12274169921875 TiB
```

**Observations/suggestions:**
1. When the capacity is narrow like 0.1 TB, the columns don't line up.  It's using \t TAB characters between columns; the y in capacity is the 32nd column; the B in TB is in the 30th column; the TAB jumps to the 33nd column rather than the 41st column (with tabstop of 8).

2. The capacities are always rounded down (fractions >= .5 are not rounding up).  That's a reasonable conservative convention for capacities, but should be documented.

3. Capacities are shown with only one decimal digit (due to calling GetDigitsStrAfterPointFromNumber() with an argument of 1).  3 digits would be more useful.  

4. A symbol indicating there is a hidden fractional amount would be helpful. That would provide a clue that displaying in smaller units is necessary to see the exact capacity.
```
134955925504 B
134955.925+ MB
134.955+ GB
0.134+ TB
128704 MiB
125.687+ GiB
0.122+ TiB
```

5. Supporting 3 and 4, show -dimm bases its capacity on a different source than SMBIOS and shows these values:
```
DimmID  Capacity
0x0011  135014383616 B
0x0011  135014.3 MB
0x0011  135.0 GB
0x0011  0.1 TB
0x0011  128759.7 MiB
0x0011  125.7 GiB
```
but the values are really:
```
135014383616 B
135014.383616 MB
135.014383616 GB
0.135014383616 TB
128759.75 MiB
125.741943359375 GiB
0.12279486656189 TiB
```
The device is not presenting exactly 135 GB, which is what "135.0 GB" suggests.

**Comment by gldiviney** [comment]
Is this still an issue in the current build?

**Comment by gldiviney** [comment]
Fixed.
