### ISSUE TITLE
Missing clear and differentiatable ipmctl version information

### ISSUE THREAD

**Issue by BeHom** [intel/ipmctl#25]
The command does not output any meaningful, differentiatable version information.
running ipmctl command on centos 7.5b after git clone and compilation.
(older version).
ipmctl version
Component                               Version
Intel DIMM Gen 1 Software Version       5.5.5.5555
Intel DIMM Gen 1 Driver Version         0.0.0.0
latest version:
ipmctl version
Intel(R) Optane(TM) DC Persistent Memory Command Line Interface Version 5.5.5.5555
Intel(R) Optane(TM) DC Persistent Memory Driver API Version 0.0.0.0
These are obviously different versions but with the same version output.
Dependencies to different versions of the NVDIMM firmware, ndctl or PMDK cannot be verified this way.
e.g ndctl version works fine

**Comment by juston-li** [comment]
The version must be passed into CMake with -DBUILDNUM=xx.xx.xx.xxxx

I"ll look into making the default version more meaningful, maybe using the most recent git tag and/or hash
