### ISSUE TITLE
Documentation errors in nvm_management.h

### ISSUE THREAD

**Issue by dchanman** [intel/ipmctl#28]
Hi there,

One example of incorrect documentation is here:
https://github.com/intel/ipmctl/blob/910c292c99dd803bb0542988e18e84b085d7a076/src/os/nvm_api/nvm_management.h#L1991

The function claims to return the number of regions when the implementation clearly returns status codes. This led to some developer errors where we were checking code like this:

```c
int num_regions = nvm_get_regions(...);
if (num_regions < 0) {
  // Expect error
}
// BUT: function actually returns a positive-integer error code, so we're getting bugs here.
```

We are now vetting our code to make sure we follow this semantic for this specific function:

```c
int count = 1;
int rc = nvm_get_regions(..., &count);
if (rc != NVM_SUCCESS) {
    // ...
}
// ...
```

One suggestion we have is to keep the api in nvm_management consistent. For example, `nvm_get_devices` actually returns the number of devices or `-1`, even though it claims to return the same `NVM_API int`. This differs from `nvm_get_regions` which returns codes and led to some bugs on our side due to confusion and documentation errors.

**Comment by juston-li** [comment]
Working on a patch now that fixes the documentation.
Functions should all be returning NVM_API codes so will also fix the couple functions that violate that to make it more consistent.

Thanks!

**Comment by juston-li** [comment]
@dchanman Wanted to run the patch by you first before mergin, see https://github.com/intel/ipmctl/pull/29.

Fixed up the documentation and made some changes to the get functions to always return NVM_API return codes. We didn't want to change any signatures but basically we enforce the routine to always use get_number_of to get the count before running the get command.

int rc = nvm_get_number_of_devices(&count);
if (rc != NVM_SUCCESS) {
    // ...
}
//allocate buffer
int rc = nvm_get_devices(buffer, count);  //count must be same as call above
if (rc != NVM_SUCCESS) {
    // ...
}

The lone exception is get_regions which for whatever reason is the only one using an in,out count.

Let me know if there you find any issues with it or have any other suggestions.

**Comment by dchanman** [comment]
Thanks for getting this done so quickly. Looks great, thank you very much.

**Comment by juston-li** [comment]
No problem! Please let us know if you have any other suggestions for nvm_api :)
