### ISSUE TITLE
IPMCTL on Windows shows DIMMs as Non-functional

### ISSUE THREAD

**Issue by kartur** [intel/ipmctl#31]
Hi,

the ipmctl.efi works properly, but when I try the ipmctl.exe from here under Windows Server 2018 (DC Edition on latest updates) it lists all nvdimms as Non-functional. I've tried multiple releases, all with the same result.

>ipmctl.exe show -dimm
```
DimmID  Capacity        HealthState     ActionRequired  LockState       FWVersion
0x0001  0.0 GiB Non-functional  N/A             N/A
0x0101  0.0 GiB Non-functional  N/A             N/A
0x1001  0.0 GiB Non-functional  N/A             N/A
0x1101  0.0 GiB Non-functional  N/A             N/A
```

I compiled IPMCTL with VS2017 und SDK/WDK version 17733.

**Comment by juston-li** [comment]
This was reported internally and being investigated now. Thanks!

**Comment by juston-li** [comment]
What BIOS version are you running

**Comment by gldiviney** [comment]
Is this still an issue in the current build?
