### ISSUE TITLE
ipmctl for Windows

### ISSUE THREAD

**Issue by krishnanmc3** [intel/ipmctl#34]
Hello All, 

We are working on migrating our applications to Windows and am trying to identify if there is an ipmctl for Windows? If yes, could someone please point me to a CLI based installer?
Thanks in advance.

**Comment by juston-li** [comment]
This project can be built for windows as a CMake project.

I am working on adding a windows installer to the github release in the next few days.

**Comment by juston-li** [comment]
Windows installer is here https://github.com/intel/ipmctl/releases/tag/v01.00.00.3231
Will include it in future releases too

**Comment by krishnanmc3** [comment]
Thank you juston-li. Could you please let me know if there is an msi version of this file available? I am working with a cli and don't have access to use gui.

**Comment by juston-li** [comment]
There is no msi version available.  I'll look into posting the raw binaries though.
