### ISSUE TITLE
Make safeclib optional

### ISSUE THREAD

**Issue by ahkok** [intel/ipmctl#36]
Also, if safeclib is required, why are there additional versions of `s_strrchr` etc? These are already provided by safeclib instead.

ideally, we avoid using all these and just properly use static code analysis and good review to make sure code is doing the right thing.

**Comment by juston-li** [comment]
Don't have the code in front of me but there might be MSVC or efi versions of s_strrchr.

The static analysis tool was the one marking these functions as unsafe and driving the requirement for safeclib  =/

**Comment by morbidrsa** [comment]
But safeclib has several problems (from my Linux Distro PoV):

1. It is another dependency we need to maintain (this includes security updates)
2. Safeclib does not look like it has a healthy community (only 5 Contriubuters and the last commit is 0 Months old)
3. Safeclib is based on functions from Annex K of the C Standard [1] which is highly controversial

So please consider either dropping safeclib or at least make it an optional dependency.

[1] http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1969.htm

**Comment by ahkok** [comment]
#39

**Comment by ahkok** [comment]
#91
