### ISSUE TITLE
Create Goal Config not allowed when device is in Frozen state

### ISSUE THREAD

**Issue by swiginton** [intel/ipmctl#38]
https://github.com/intel/ipmctl/blob/63b8823b326b6e25be4e63e480faf12a4a0025f6/DcpmemPkg/driver/Core/NvmSecurity.c#L234

Why is that?  Why not allow a goal configuration to occur if the device is frozen?  Shouldn't this read:
IsAllowed = ((SECURITY_DISABLED == SecurityState) || (SECURITY_FROZEN == SecurityState)) ? TRUE : FALSE;

**Comment by juston-li** [comment]
Also reproduces when security is NOT_SUPPORTED
