### ISSUE TITLE
Error: There is not enough memory to complete the requested operation

### ISSUE THREAD

**Issue by jessehui** [intel/ipmctl#39]
Hi, 

I installed ipmctl on a new environment and received below response:
```shell
~# ipmctl list

Error: There is not enough memory to complete the requested operation.
```
No matter what instruction I use, it always throws this. However, I use /proc/meminfo and see there is a lot of memory space actually. Never seen this before. Does anyone know why?

### Environment:
- OS:  `Ubuntu 18.04.1 (kernel: 4.15.0-33-generic)`
- ipmctl commit : `63b8823b326b6e2`

**Comment by juston-li** [comment]
Could you attach the debug logs after running a couple commands?

'ipmctl set -preferences DBG_LOG_LEVEL=4'
Run some commands that trigger the error
Attach the debug log located in /var/log/ipmctl/debug.log (or possibly in the directory you executed ipmctl if you compiled ipmctl)

**Comment by jessehui** [comment]
When I run 
`ipmctl set -preferences DBG_LOG_LEVEL=4`
it still gives me 
`Error: There is not enough memory to complete the requested operation`.

However, I tried to get in efi shell mode and it looks like there is ipmctl.efi installed. I can configure NVDIMM here. SO is there conflict between linux ipmctl and efi ipmctl? Thanks.

**Comment by juston-li** [comment]
Hmm you can manually change that in: /etc/ipmctl.conf
Not sure if there will be much debug log though, looks like it isn't able to allocate memory at all.

Did you compile ipmctl or did you install the package from https://launchpad.net/~jhli/+archive/ubuntu/ipmctl?

There's no conflict between efi and os ipmctl, you can use both.

**Comment by jessehui** [comment]
Yeah. The debug level didn't help. The os ipmctl is installed from source. 
I can use efi ipmctl to configure. Everything fine. But if I use os ipmctl, the error ejects.

**Comment by kellycouch** [comment]
Jesse - did you also build libsafec from source? By default, internal buffers used to copy are too small for this project, so it must be adjusted to a larger size.

**Comment by Maciuch** [comment]
Hi @juston-li , any idea how to fix this for Clear Linux.
Behavior is exactly as described here. All is installed from bundles

dbaas@clr-dc8df3b2ba2d44bf88c1bde1ac2ae1aa ~ $ uname -a
Linux clr-dc8df3b2ba2d44bf88c1bde1ac2ae1aa 4.19.4-663.native #1 SMP Fri Nov 23 15:33:50 UTC 2018 x86_64 GNU/Linux

dbaas@clr-dc8df3b2ba2d44bf88c1bde1ac2ae1aa ~ $ sudo swupd search ipmctl
Password:
Searching for 'ipmctl'

Bundle storage-utils    [installed]     (252 MB on system)
        /usr/lib64/libipmctl.so.3.1.0
        /usr/bin/ipmctl-monitor
        /usr/bin/ipmctl
        /usr/share/package-licenses/ipmctl/ShellPkg_License.txt
        /usr/share/package-licenses/ipmctl/MdePkg_License.txt
        /usr/share/package-licenses/ipmctl/MdeModulePkg_Universal_RegularExpressionDxe_Oniguruma_COPYING
        /usr/share/package-licenses/ipmctl/MdeModulePkg_License.txt
        /usr/share/package-licenses/ipmctl/MdeModulePkg_Library_BrotliCustomDecompressLib_LICENSE
        /usr/share/package-licenses/ipmctl/LICENSE
        /usr/share/package-licenses/ipmctl/BaseTools_Source_C_BrotliCompress_LICENSE
        /usr/share/package-licenses/ipmctl/BaseTools_License.txt
        /usr/share/man/man1/ipmctl.1.gz
        /usr/share/man/man1/ipmctl-version.1.gz
        /usr/share/man/man1/ipmctl-update-firmware.1.gz
        /usr/share/man/man1/ipmctl-show-topology.1.gz
        /usr/share/man/man1/ipmctl-show-system-capabilities.1.gz
        /usr/share/man/man1/ipmctl-show-socket.1.gz
        /usr/share/man/man1/ipmctl-show-sensor.1.gz
        /usr/share/man/man1/ipmctl-show-region.1.gz
        /usr/share/man/man1/ipmctl-show-preferences.1.gz
        /usr/share/man/man1/ipmctl-show-performance.1.gz
        /usr/share/man/man1/ipmctl-show-memory-resources.1.gz
        /usr/share/man/man1/ipmctl-show-host.1.gz
        /usr/share/man/man1/ipmctl-show-goal.1.gz
        /usr/share/man/man1/ipmctl-show-firmware.1.gz
        /usr/share/man/man1/ipmctl-show-events.1.gz
        /usr/share/man/man1/ipmctl-show-error-log.1.gz
        /usr/share/man/man1/ipmctl-show-device.1.gz
        /usr/share/man/man1/ipmctl-show-acpi.1.gz
        /usr/share/man/man1/ipmctl-run-diagnostic.1.gz
        /usr/share/man/man1/ipmctl-modify-device.1.gz
        /usr/share/man/man1/ipmctl-load-goal.1.gz
        /usr/share/man/man1/ipmctl-inject-error.1.gz
        /usr/share/man/man1/ipmctl-help.1.gz
        /usr/share/man/man1/ipmctl-erase-device-data.1.gz
        /usr/share/man/man1/ipmctl-enable-device-security.1.gz
        /usr/share/man/man1/ipmctl-dump-support-data.1.gz
        /usr/share/man/man1/ipmctl-dump-goal.1.gz
        /usr/share/man/man1/ipmctl-dump-debug-log.1.gz
        /usr/share/man/man1/ipmctl-delete-goal.1.gz
        /usr/share/man/man1/ipmctl-create-goal.1.gz
        /usr/share/man/man1/ipmctl-change-sensor.1.gz
        /usr/share/man/man1/ipmctl-change-preferences.1.gz
        /usr/share/man/man1/ipmctl-change-device-security.1.gz
        /usr/share/man/man1/ipmctl-change-device-passphrase.1.gz
        /usr/share/man/man1/ipmctl-acknowledge-event.1.gz
        /usr/share/ipmctl/ipmctl.conf
        /usr/lib64/libipmctl.so.3
        /usr/lib/systemd/system/ipmctl-monitor.service
        /usr/etc/logrotate.d/ipmctl.conf

Bundle storage-utils-dev        (4517 MB to install)
        /usr/lib64/pkgconfig/libipmctl.pc
        /usr/lib64/libipmctl.so

dbaas@clr-dc8df3b2ba2d44bf88c1bde1ac2ae1aa ~ $ sudo swupd search libsafec
Searching for 'libsafec'

Bundle storage-utils    [installed]     (252 MB on system)
        /usr/share/doc/libsafec/COPYING
        /usr/lib64/libsafec-3.3.so.3.0.3
        /usr/lib64/libsafec-3.3.so.3

Bundle storage-utils-dev        (4517 MB to install)
        /usr/lib64/libsafec-3.3.so
        /usr/include/libsafec/safe_types.h
        /usr/include/libsafec/safe_str_lib.h
        /usr/include/libsafec/safe_mem_lib.h
        /usr/include/libsafec/safe_lib_errno.h
        /usr/include/libsafec/safe_lib.h
        /usr/include/libsafec/safe_config.h
        /usr/include/libsafec/safe_compile.h

I've tried also to add storage-utils-dev bundle, but it didn't change a thing.

**Comment by gldiviney** [comment]
Maciej - Juston has moved to a different project. Did you try the last step mentioned by Kelly?

**Comment by kellycouch** [comment]
Please try building libsafec with the configure step including flag to use larger string buffer '--enable-strmax=0x8000'.
An example spec file can be found here: https://build.opensuse.org/package/view_file/home:jhli/safeclib/libsafec.spec?expand=1

**Comment by Maciuch** [comment]
I'm sure I could build libsafec, and it would work.
But anyways Clear Linux shouldn't have .so included that does not work. Do you have any contact to that project, or should we rise there an issue?

**Comment by kellycouch** [comment]
Hi – we’re leaning towards changing default build to download and statically link libsafec. This should resolve yours and other distribution issues we are facing with libsafec. Concerns?

**Comment by Maciuch** [comment]
Sounds good

**Comment by kiendinh** [comment]
Hi,
I'm using Clear Linux v28260 and still have the same issue. libsafec is included in the storage-utils-dev package. May I know if the issue has been solved?

Thanks

**Comment by gldiviney** [comment]
Not by default. Can you try ensuring you're using a build command that includes options like this?

cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_AS_DLL=OFF -DSAFECLIB_SRC_DOWNLOAD_AND_STATIC_LINK=ON

**Comment by ahkok** [comment]
@kellycouch we really need to remove libsafec, and statically linking it just further increases technical debt. This has gone on long enough?

**Comment by ahkok** [comment]
#91

**Comment by gldiviney** [comment]
This is a side-effect of supporting multiple environments. We're looking at what would make the most sense for all going forward. Stay tuned.
