### ISSUE TITLE
ipmctl option to clear StagedFWVersion 

### ISSUE THREAD

**Issue by Venkata-S** [intel/ipmctl#40]
An option to clear StagedFWVersion  might be useful in scenario where user wants to avoid activating new version after doing load (eg user error).  In the absence of this option, the next power cycle will make the staged version to be the active one.  One work-around is for user to run load command again.  But an explicit option may come in handy in some cases where there are multiple dimms in a server and user realizes they want to roll back after starting to update.

**Comment by kellycouch** [comment]
I understand the request, however this is not possible given implementation today and thus is not planned to be fixed. Present implementation requires a reboot before another FW image can be staged. If this is a must-have feature, please pursue this with your Intel PAE or email me directly and I can assist in initiating this request internally.
