### ISSUE TITLE
Viral Policy information unsupported

### ISSUE THREAD

**Issue by dchanman** [intel/ipmctl#45]
In https://github.com/intel/ipmctl/pull/43 I added some logic to not error out when calling unsupported commands. I believe I found a related issue.

In the latest release v01.00.00.3262, `DIMM_INFO_CATEGORY_VIRAL_POLICY` was added in commit https://github.com/intel/ipmctl/commit/989c1b82cea191e4eb8623686df68c3b26281554. Since then, our code for configuring regions using the toplevel ipmctl API `nvm_get_device_details()` has broken.

`nvm_get_device_details()` is returning an error because our firmware appears to not support retrieval of viral policy. In https://github.com/intel/ipmctl/blob/50b544e98e7dd9b1a70d2c53b266efe46a983173/src/os/nvm_api/nvm_management.c#L933 the parameter `DIMM_INFO_CATEGORY_ALL` is provided. There seems to be no check for whether viral policy is supported or not, and since fetching viral policy fails, `nvm_get_device_details()` fails.

`nvm_get_device_details()` should be fixed to either poll and respect the capabilities reported by the firmware, or ignore info categories which could potentially be unsupported. We can workaround for now by commenting out the invocations of `FwCmdGetViralPolicy()`.

**Comment by juston-li** [comment]
Get Viral policy was moved to its on FW command. It's supported in FIS 1.2. Please update to the latest firmware.

Apologies for not maintaining backwards compatibility, we will do our best to address it in future releases.
