### ISSUE TITLE
ipmctl show -sensor return failure

### ISSUE THREAD

**Issue by insanecoderr** [intel/ipmctl#46]
ipmctl tag:v01.00.00.3102

ipmctl show -sensor return:
"Failed to read the sensors or thresholds values from DIMM 49. Code %r"

**Comment by juston-li** [comment]
What version of FW are you using?

Also, it was a while back but I recall one of releases had an issue with show -sensor. I believe it was fixed by https://github.com/intel/ipmctl/commit/394308c984e19b0e0a2f95c31b3d973cae7c708f
