### ISSUE TITLE
Install, and search for, `ipmctl.conf` in proper paths.

### ISSUE THREAD

**Issue by ahkok** [intel/ipmctl#47]
Problem: currently, by default, `ipmctl.conf` is installed by the package in `/<prefix>/etc/ipmctl.conf`, which results in `/usr/etc/` and is ... definitely wrong.

Better to search for, and use, the config file in several places and include a distribution-wide config location as a fallback, and only install the package default config into that location. Packages should not install files in `/etc` if it can be avoided (so, never).

The code in `ini.c` should scan, in order, in these locations for an `ipmctl.conf` file, and process the first file found:

`pwd -P` # this is what the code does
`/etc/ipmctl.conf` # this one is missed
`<prefix>/etc/ipmctl.conf` # this is what the code does
`<prefix>/usr/share/ipmctl/ipmctl.conf` # this one needs adding

Something like the following things are needed:

```
#define INI_DEFAULT_INSTALL_FILEPATH "/usr/share/ipmctl/"
```

```
snprintf(g_ini_path_filename, sizeof(g_ini_path_filename), "%s%s", INI_INSTALL_FILEPATH, p_ini_file_name);
```

```
snprintf(g_ini_path_filename, sizeof(g_ini_path_filename), "%s%s%s", APP_DATA_FILE_PATH, INI_DEFAULT_INSTALL_FILEPATH, p_ini_file_name);
```

Then, adjust the `make install` rules to install the sample config file only into `INI_DEFAULT_INSTALL_FILEPATH`.

**Comment by mplucins** [comment]
thanks for your comment, we have moved the ipmctl.conf file to the suggested location
