### ISSUE TITLE
Make reboot message be OS-specific

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#49]
`DcpmPkg/cli/ShowGoalCommand.c:    Print(FORMAT_STR_NL, L"A reboot is required to process new memory allocation goals.");`

The name of the command to trigger a reboot varies by OS:
- UEFI shell: reset
- Windows: restart   ("shutdown /r")
- linux: reboot

**Suggestion:**
Make the print be OS-specific.
Print(FORMAT_STR_NL, L"A reset is required to process new memory allocation goals.");
Print(FORMAT_STR_NL, L"A restart (shutdown /r) is required to process new memory allocation goals.");
Print(FORMAT_STR_NL, L"A reboot is required to process new memory allocation goals.");

**Comment by gldiviney** [comment]
Thanks for the suggestion! We will consider it.
