### ISSUE TITLE
show -system NFIT doesn't print SMBIOS Management Information structure

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#5]
show -system NFIT doesn't decode the NFIT SMBIOS Management Information structure.  It should decode the data.

Output:
```
Type: 0x3
Length: 0x20
TypeEquals: Smbios
```

Code:
```
  case NVDIMM_SMBIOS_MGMT_INFO_TYPE:
    Print(L"TypeEquals: Smbios\n"
        );
    break;
```
acpidump -b, iasl -d nfit.dat does not decode them either, but shows the raw contents. On one system those are reported as:
```
[970h 2416   2]                Subtable Type : 0003 [SMBIOS Information]
[972h 2418   2]                       Length : 0020

[974h 2420   4]                     Reserved : 00000000
[008h 0008  24]         SMBIOS Table Entries : \
    20 00 22 00 24 00 25 00 27 00 29 00 2C 00 2E 00 \
    30 00 31 00 33 00 35 00
```
Those are 2-byte SMBIOS handle values, pointing to the type 17 records corresponding to the NVDIMMs.  That data is incorrect; it's supposed to be reporting raw SMBIOS record data (that dmidecode parses).  So, this should confuse ipmctl and result in an error message as it tried to parse the record as:
- 1 byte Type (e.g., 17)
- 1 byte Length 
- 2-byte Handle
- variable length data for the record

Limited decode would suffice for ipmctl - let dmidecode do the full decoding.
- Type: display this
- Length: to process all the records
- Handle: display this
- Locator: already parsed by ipmctl for show -topology
- Bank Locator: already parsed by ipmctl for show -topology
- Manufacturer: already parsed by ipmctl for show -topology

Add an option to output the content to a binary file that dmidecode --from-dump can parse in more detail.

**Comment by juston-li** [comment]
So you're saying the SMBIOS Table Entries is incorrect?

This is on my system
`
[BB0h 2992   2]                Subtable Type : 0003 [SMBIOS Information]
[BB2h 2994   2]                       Length : 0020

[BB4h 2996   4]                     Reserved : 00000000
[008h 0008  24]         SMBIOS Table Entries : \
    21 00 25 00 29 00 2F 00 33 00 37 00 3D 00 41 00 \
    45 00 4B 00 4F 00 53 00
`
That it should have the structure defined in SMBIOS 3.2 7.18 Memory Device (Type 17) there?

**Comment by gldiviney** [comment]
Is this still an issue?

**Comment by kellycouch** [comment]
Closed due to inactivity.

**Comment by kellycouch** [comment]
Use OS based tools to decode SMBIOS. On Linux for example, use 'dmidecode'.
