### ISSUE TITLE
Random region id getting generated

### ISSUE THREAD

**Issue by Surbhishree30** [intel/ipmctl#53]
Random region id is getting generated for creating namespace and is getting changed after creating the goal again on the same server.
Steps followed
1.In the UEFI shell, create goal
2.Reboot the server
3.Again go to UEFI shell prompt check for region using "ipmctl show -region" - The region id getting generated here are random numbers and not from 0
4.Create namespace using region id and reboot the server
5.Delete the existing goal and namespace
6.Create new goal
7.Reboot the server
8.Again check for region - the region id generated will be random and different from the previous one.

**Comment by kellycouch** [comment]
The region ID being displayed is not random, as it may appear. It is directly derived from the Interleave Set Index. We will consider changing regionId to use normalized values, starting at 0 or 1.

**Comment by kellycouch** [comment]
Please see version 2.x. Namespace and Region IDs are not random.
