### ISSUE TITLE
`show -goal` doesn't show the current goal after reboot

### ISSUE THREAD

**Issue by patr-geary-smci** [intel/ipmctl#56]
This is with latest commit ipmctl.

The running goal information is not dumped as part of `show -goal` after a reboot, however the goal settings appear to be utilized correctly.

I know that you reference regions after goals have been set; but it would be useful to have this data on hand after the fact.

```
[root@101-249 ~]# ipmctl create -goal -socket 0x0000 MemoryMode=50 PersistentMemoryType=AppDirectNotInterleaved

The following configuration will be applied:

SocketID        DimmID  MemorySize      AppDirect1Size  AppDirect2Size
0x0000          0x0001  246.0 GiB               256.0 GiB       0.0 GiB
0x0000          0x0101  246.0 GiB               256.0 GiB       0.0 GiB
Do you want to continue? [y/n] y
Created following region configuration goal
SocketID        DimmID  MemorySize      AppDirect1Size  AppDirect2Size
0x0000          0x0001  246.0 GiB               256.0 GiB       0.0 GiB
0x0000          0x0101  246.0 GiB               256.0 GiB       0.0 GiB
A reboot is required to process new memory allocation goals.
[root@101-249 ~]# reboot

*reboot happens*

[root@101-249 ~]# ipmctl show -goal

There are no goal configs defined in the system.
Please use 'show -region' to display currently valid persistent memory regions.
```

**Comment by kellycouch** [comment]
Goal is a request for change in configuration. After is has been applied, a goal request no longer exists. You can use commands Show Region and Show Memory Resources to view the configuration after a goal request.

Show Goal may be used prior to reboot, because the goal request has not been applied or acted on yet.

**Comment by patr-geary-smci** [comment]
I understand; I mentioned the `show -region` stuff at the bottom because the execution of goal pointed me to it.


I just think it'd be best for everyone long term if they could pull the data from where they're setting it (Since `show -goal` will feed valid data until reboot.)


IMHO it significantly aids in administration if everything is in the exact same place, and removes the need for me to, after a reboot, do a separate algorithm to see how everything was configured and guestimate numbers.


If ya'll don't feel it's of any value, please close the issue.
