### ISSUE TITLE
ipmctl shows that the nvdimm is "non-functional"

### ISSUE THREAD

**Issue by insanecoderr** [intel/ipmctl#59]
ndctl version:61.2
ipmctl version:01.00.00.3279

the nvdimm is intel optane DC Pmem(512G version).

in UEFI shell, the tool provided by intel(ipmctl.efi) can find the nvdimm in heathy state. However,in OS,"ndctl list -D" can not show any information.

Moreover,the ipmctl tool which is provided by INTEL shows that the dimm is non-functional which may be a wrong interpretation since the dimm is actually functional as the UEFI tool shows.

So,can u help me with this?

**Comment by gldiviney** [comment]
Thanks - Can you try on a later build? Also, can you provide some details on the BIOS you're using?

**Comment by insanecoderr** [comment]
the version is 6.07 provided by insyde
