### ISSUE TITLE
Is there any details doc about the usage of ipmctl-cli

### ISSUE THREAD

**Issue by ConeyLiu** [intel/ipmctl#62]
I want to know if there is any details doc about the impctl-cli. Thanks in advance.

**Comment by gldiviney** [comment]
Yes - In the documentation folder (https://github.com/intel/ipmctl/tree/master/Documentation/ipmctl) there is a wealth of information about this system. Is there something more specific you're looking for?

**Comment by ConeyLiu** [comment]
Thanks for the answer, maybe you can add those to the README or wiki.

**Comment by gldiviney** [comment]
Thanks - we will look into this
