### ISSUE TITLE
Remove dependency on PMTT ACPI table; use HMAT instead

### ISSUE THREAD

**Issue by swiginton** [intel/ipmctl#63]
https://github.com/intel/ipmctl/blob/f28a8f7ce302664a7d3389e84a0eca734ed63628/DcpmPkg/driver/Utils/AcpiParsing.c#L339

HMAT was created to overcome the deficiencies of PMTT and should replace it in more up to date ACPI implementations

**Comment by gldiviney** [comment]
Thanks - will review

**Comment by gldiviney** [comment]
Is this still an issue or can we close?

**Comment by swiginton** [comment]
Sorry...meant to update this before the holidays.

HMAT is the newer, more dynamic way to communicate this information.  Is there a reason why the iMC needs to be known at the OS level?  HMAT does associate latency and bandwitdth info for a given SPA.  From the OS point of view, the actual iMC identifier shouldn't matter.

The tool gracefully handles when the PMTT ACPI table is not present on a given system, so that would imply that this isn't essential.

If the tool simply wants a DIMM-to-iMC correlation, a UEFI protocol would seem to be an easier way to do for the Shell version of the tool.  I an see the desire for using ACPI tables because for OS-versions of the tool.

Again, this is imply an enhancement request.  I believe we are going to have more systems implement HMAT tables than PMTT tables in the future, so take that for what it is.

Thanks!

**Comment by kellycouch** [comment]
Update: PMTT is a requirement for Intel Optane Persistent Memory. Closing.
