### ISSUE TITLE
APPDIRECT_GRANULARITY_DEFAULT should be APPDIRECT_GRANULARITY_32GIB

### ISSUE THREAD

**Issue by swiginton** [intel/ipmctl#64]
https://github.com/intel/ipmctl/blob/f28a8f7ce302664a7d3389e84a0eca734ed63628/DcpmPkg/cli/ShowPreferencesCommand.c#L138

**Comment by gldiviney** [comment]
Thanks - will review

**Comment by kellycouch** [comment]
Fixed on testing: 19ae58275587118bcd41529f0b5259ee210b5785
https://github.com/intel/ipmctl/commit/19ae58275587118bcd41529f0b5259ee210b5785

Removed the config file value 'Recommended', using discrete value 1 or 32 instead. 
Updated line per suggestion.
Default is now 1GB alignment.
