### ISSUE TITLE
Possible to miss interleave sets with same index value

### ISSUE THREAD

**Issue by swiginton** [intel/ipmctl#65]
https://github.com/intel/ipmctl/blob/f28a8f7ce302664a7d3389e84a0eca734ed63628/DcpmPkg/driver/Core/Region.c#L548

This logic makes it possible to miss adding interleave sets into the internal data structures if a DCPMM is added with existing metadata in the PCD from being configured on another system (or previously on the same system).  It is possible to have more than one DCPMM on the system with the Interleave Set Index in the DIMM Interleave Information Table portion of the PCD set to the same index in this way.

Although this would not happen when all DCPMMs are configured at the same time on the same system, it limits the robustness of the tools (and UEFI driver) for migration cases.

**Comment by kellycouch** [comment]
Thanks for the comment. We are aware of this and a fix is planned.

**Comment by swiginton** [comment]
This appears to have been addressed in the 1.0.0.3354 release of ipmctl.  Can that be confirmed?

**Comment by swiginton** [comment]
It was a rumor from a user...  Since I did not see relevant changes from this file, I was confused.  Thanks for confirming, though!

**Comment by swiginton** [comment]
Confirm that this was addressed with at least the 1.0.03373 release.
