### ISSUE TITLE
IPMCTL for windows not working from SSH

### ISSUE THREAD

**Issue by nimmy-23** [intel/ipmctl#67]
I have installed the ipmctl_windows_install-01.00.00.3344.exe for using ipmctl in windows.
It works fine in the system, but when i do an ssh to the same system and try to run ipmctl it gives me an error: "Failed to intialize nvm library (267): Unknown".

I have added the path in the environmental variable but still am getting the same error message.

Could someone help me on this?

**Comment by gldiviney** [comment]
Sure - which version of windows is this? Can you paste the output of the 'ver' command?

Also, please list the contents of the directory where ipmctl is installed when this occurs

**Comment by gldiviney** [comment]
Also, what SSH system are you employing for this?

**Comment by nimmy-23** [comment]
We tried it on WS2012R2, WS2016 and WS2019 and on all three we got the same error.
WS2012: Microsoft Windows [Version 6.3.9600]
WS2016: Microsoft Windows [Version 10.0.14393]
WS2019: Microsoft Windows [Version 10.0.17763.1]

Following are the contents of the directory where ipmcl is installed:
![ipmctl_contents](https://user-images.githubusercontent.com/44996557/48550760-7d4a0780-e888-11e8-9384-44e93beb5495.JPG)

We are using putty for doing SSH.

**Comment by nimmy-23** [comment]
Could to please share the script for SetEnvironmentVar.exe

**Comment by gldiviney** [comment]
I mean which SSH host do you have running on the target side - Cygwin/OpenSSH/etc...? 

Are you able to run IPMCTL commands locally on the target as expected?

**Comment by nimmy-23** [comment]
Locally on the target it works as expected.

 We used OpenSSH and MSYS2, from both we are getting the same error:"Failed to intialize nvm library (267): Unknown"

**Comment by nimmy-23** [comment]
Can I know what SetEnvironmentVar does or get the script for it?

**Comment by gldiviney** [comment]
Thanks

The SetEnvironmentVar is only used during installation and is not officially supported. It may provide some tips/help if you call it without any arguments

Have you tried uninstalling and reinstalling on the same machine? If the app works locally but not via SSH, it sounds like an SSH environmental problem. We tried getting some SSH tools working on Windows but it did not perform well enough (in general) for production use. I will try using our latest code with it and see how it does.

**Comment by nimmy-23** [comment]
Am not able to run any commands from ssh. I tried uninstalling and installing ipmctl again, but still same error. 

I have observed that sometime the uninstaller.exe is not generated while ipmctl is installed and sometimes it is present.

**Comment by nimmy-23** [comment]
Installation and uninstallation is done locally on the machine non of these is done from ssh.

Today I have installed ipmctl freshly on a machine and uninstaller.exe was not present.  
And on another machine which already had ipmctl I have uninstalled it and reinstalled in a different location and saw that uninstaller.exe was missing.

**Comment by gldiviney** [comment]
Did these machines have older versions of our software installed?

Try this - Delete the contents of "C:\Program Files\Intel\DCPM Software" (you may have to kill "ipmctl_monitor.exe"). Then try installing again and let me know if the "uninstaller.exe" file appears.

**Comment by nimmy-23** [comment]
I deleted the contents of "C:\Program Files\Intel\DCPM Software" and installed the latest ipmctl "ipmtl_windows_install-01.00.00.3364.exe". Still not finding the "uninstaller.exe".


Is it always required to install ipmctl in the default location "C:\Program Files\Intel\DCPM Software" or is it fine to install it in  any custom location as per our requirement?

**Comment by gldiviney** [comment]
This is very strange. How many computers are affected by this and showing the same symptoms?

**Comment by nimmy-23** [comment]
I have checked on 3 systems and on all three this issue is found

**Comment by gldiviney** [comment]
Are you running the installer with Administrator privileges?

**Comment by nimmy-23** [comment]
Yes

**Comment by gldiviney** [comment]
Ok - just to ensure we're talking about the same thing: the current issue we're talking about is the uninstaller.exe file missing, not the SSH commands not working, right?

If this is the case, given the image above where the file is present, does that machine now show an install without this file?

**Comment by nimmy-23** [comment]
In order to make ipmctl tool work over ssh you have suggested to uninstall it and reinstall with the latest .exe file released. I have done that and found that uninstaller.exe was not present. But still the tool worked properly from machine but still failed over ssh.  

And for WS2012 R2 as I have mentioned earlier ipmctl tool didn't work properly.  Even the ourput of command "ipmctl show -memoryresource"  gave 0 for all the feilds

**Comment by gldiviney** [comment]
Ok - thanks

For SSH - this is an environmental issue. Our tool doesn't explicitly support or require SSH in any way. We cannot comment on what might be wrong with the machine in question to produce the effect that use over SSH doesn't work except to say that SSH on windows is generally known to be a problem. I don't think we can be of any help here within the scope of this project.

For the installer - Since it deploys and is usable, it sounds like the only remaining issue might be that it isn't dropping the uninstaller.exe. This will break the uninstall process - I will open a seperate issue for this.

Lastly, it seems that something is confusing the software in the WS2012 environment. Can you uninstall the software (or manually stop ipmctl_monitor.exe and delete the program files space), then ensure there aren't any files starting with "ipmctl" in "C:\Program Files\Intel" or in "C:\Users\[NAME]\AppData\Roaming\Intel\ipmctl." Then reinstall and try again.

**Comment by nimmy-23** [comment]
Thanks...

I will reinstall it in ws2012 again.

But you previously told that some of the simple commands worked for you over ssh. Have to exported any path in order to achieve this.

**Comment by gldiviney** [comment]
I opened https://github.com/intel/ipmctl/issues/68 - please direct installer issue details there

**Comment by nimmy-23** [comment]
ipmctl is working properly now in WS2012 after uninstalling and reinstalling again as suggested.

**Comment by nimmy-23** [comment]
Even over SSH ipmctl is working now.

Thanks for the help...
