### ISSUE TITLE
Installer does not always drop the Uninstaller.exe file

### ISSUE THREAD

**Issue by gldiviney** [intel/ipmctl#68]
This will complicate an explicit uninstall. The conditions under which this file is not dropped are not clear and we have not replicated this outside of a virgin install on any given machine (all subsequent installs work so far)

**Comment by nimmy-23** [comment]
I have installed the new ipmtl_windows_install-01.00.00.3364.exe freashly on a system and also reinstalled on the systems which already had ipmctl and in both the cases i was unable to fild the uninstaller.exe

Contents of folder:
![ipmctl_contents_new](https://user-images.githubusercontent.com/44996557/48931509-8f8cfc80-eeab-11e8-948e-1a9a9d1de2b3.JPG)

**Comment by gldiviney** [comment]
Thanks - will try to replicate

**Comment by gldiviney** [comment]
Is this still an issue or can we close?

**Comment by kellycouch** [comment]
Fix planned.

**Comment by gldiviney** [comment]
Fixed
