### ISSUE TITLE
PMTT ACPI table missing now causes driver to not load

### ISSUE THREAD

**Issue by swiginton** [intel/ipmctl#69]
https://github.com/intel/ipmctl/blob/2354bee109605b8118a38a248c6472035d58e1ed/DcpmPkg/driver/Protocol/Driver/NvmDimmConfig.c#L4180

Introduced with 1.0.0.3373 drop.  When called by initAcpiTables(), the returned error code causes the driver to not load.  The PMTT tables only only being used by ParseAcpiTables() to see if memory mode is allowed, but defaults to TRUE if these tables aren't present.

This should not be a fatal error.

**Comment by gldiviney** [comment]
The fix for this is staged for the next release. It is also on the testing branch at hash 5cb2cc4910ca6974aef66da22949f5634bf75b39 if you want to try it before the official drop. If this is sufficient, please close this issue.

**Comment by swiginton** [comment]
Confirmed fix with 1.0.0.3380 release
