### ISSUE TITLE
veryfication typo

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#7]
Spelling error in the word "verification":

DcpmemPkg/driver/Core/Diagnostics/FwDiagnostic.c:    NVDIMM_DBG("Dimm 0x%x time veryfication diagnostic test: success", pDimm->DeviceHandle.AsUint32);

**Comment by juston-li** [comment]
Fixed in 530385dacd3ae564102b7ae4125a7de2c6ae39ff

Thanks!
