### ISSUE TITLE
How to uninstall the tool before want to install newer?

### ISSUE THREAD

**Issue by MagicVin** [intel/ipmctl#70]
I tried the "make uninstall" command, but it doesn't work.
tests as below:
`[root@skl64 ipmctl]# make uninstall`
`make: *** No rule to make target `uninstall'.  Stop.`
So,Is there a way to remove the tool ?

**Comment by gldiviney** [comment]
Which specific environment are you working in?

**Comment by MagicVin** [comment]
CentOS 7.5/ WW48 BKC/4.18.8 kernel

**Comment by gldiviney** [comment]
Thanks - We will look into this.

**Comment by juston-li** [comment]
cmake doesn't support make uninstall, or at least I couldn't get it to work.

It does have a install_manifest.txt, so removing everything in that file would be equivalent to uninstalling
xargs rm < install_manifest.txt

**Comment by MagicVin** [comment]
Ok, thank your suggestion!
