### ISSUE TITLE
The /etc/logrotate.d/ipmctl.conf file has CR/LF line endings

### ISSUE THREAD

**Issue by JohnMalmberg** [intel/ipmctl#71]
The /etc/logrotate.d/ipmctl.conf file has CR/LF line endings which is causing logrotate problems.
~~~
Installed Packages
ipmctl.x86_64                  01.00.00.3374-1.el7                  @jhli-ipmctl
 uname -r
3.10.0-862.14.4.el7.x86_64
cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)

**Comment by gldiviney** [comment]
Thanks, we'll address

**Comment by gldiviney** [comment]
Is this still an issue on the lastest builds?

**Comment by knweiss** [comment]
I've only tested the latest release package [v01.00.00.3455](https://github.com/intel/ipmctl/releases/tag/v01.00.00.3455) and it still has the problem.

This is the error message of the daily `logrotate` cron job:

```
/etc/cron.daily/logrotate:

error: ipmctl.conf:1 lines must begin with a keyword or a filename (possibly in double quotes)
error: ipmctl.conf:6, unexpected text after }
```

I've fixed it locally with the command `dos2unix /etc/logrotate.d/ipmctl.conf`.
