### ISSUE TITLE
snprintf overflow in nvm_management.c

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#72]
Compiling the master or testing branch right now on SUSE Linux Enterprise Server 15 results in:

```
ipmctl/src/os/nvm_api/nvm_management.c: In function ‘nvm_get_sw_inventory’:
ipmctl/src/os/nvm_api/nvm_management.c:330:61: error: ‘%s’ directive output truncated writing 26 bytes into a region of size 25 [-Werror=format-truncation ]
   snprintf(p_inventory->mgmt_sw_revision, NVM_VERSION_LEN, "%s", VERSION_STR);
                                                             ^~
compilation terminated due to -Wfatal-errors.

```

**Comment by kellycouch** [comment]
VERSION_STR is provided at build time. It can be changed to whatever is appropriate, but cannot exceed the size of NVM_VERSION_LEN.

Backtracking, 
#define VERSION_STR STRINGIZE(__VERSION_NUMBER__)

from CMakeList.txt
-D__VERSION_NUMBER__=${IPMCTL_VERSION_STRING}

if(BUILDNUM)
	set(IPMCTL_VERSION_STRING ${BUILDNUM})
else()
...
    Use git describe --dirty to pull the tag of this commit and use it for version

So, either need to ensure BUILDNUM is set when invoking the build OR ensure the tag is valid. Expected it to be in format: CR_MGMT_1.XX.XX.XXXX.

Ensuring either of these values are correct should resolve your issue.

**Comment by RobertCElliott** [comment]
I'm just running the sequence per README.md:
```
mkdir output && cd output
cmake -DRELEASE=ON -DCMAKE_INSTALL_PREFIX=/ ..
make -j all
sudo make install
```

git does output 26 characters, not resembling CR_MGMT_1.XX.XX.XXXX:
```
git describe --dirty
v01.00.00.3279-148-g5cf9c1e
```

and is what __VERSION_NUMBER__ is set to:
```
./CMakeFiles/ipmctl.dir/DependInfo.cmake:  "__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e"
./CMakeFiles/ipmctl.dir/flags.make:C_DEFINES = -DHAVE_C99 -DOS_BUILD -DPCD_CACHE_ENABLED -DPLAYBACK_RECORD_SUPPORTED -D_GNU_SOURCE -D__LINUX__ -D__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e -Dipmctl_EXPORTS
./CMakeFiles/ipmctl_os_interface.dir/DependInfo.cmake:  "__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e"
./CMakeFiles/ipmctl_os_interface.dir/flags.make:C_DEFINES = -DHAVE_C99 -DOS_BUILD -DPCD_CACHE_ENABLED -DPLAYBACK_RECORD_SUPPORTED -D_GNU_SOURCE -D__LINUX__ -D__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e
./CMakeFiles/ipmctl-bin.dir/DependInfo.cmake:  "__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e"
./CMakeFiles/ipmctl-bin.dir/flags.make:C_DEFINES = -DHAVE_C99 -DOS_BUILD -DPCD_CACHE_ENABLED -DPLAYBACK_RECORD_SUPPORTED -D_GNU_SOURCE -D__LINUX__ -D__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e
./CMakeFiles/ipmctl-monitor.dir/DependInfo.cmake:  "__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e"
./CMakeFiles/ipmctl-monitor.dir/flags.make:CXX_DEFINES = -DHAVE_C99 -DOS_BUILD -DPCD_CACHE_ENABLED -DPLAYBACK_RECORD_SUPPORTED -D_GNU_SOURCE -D__LINUX__ -D__VERSION_NUMBER__=01.00.00.3279-148-g5cf9c1e
```

**Comment by kellycouch** [comment]
Looks like git is adding some unexpected characters to the end of the tag. You should be able to WA this by providing the same build number via 
cmake **-DBUILDNUM=01.00.00.3279** -DRELEASE=ON -DCMAKE_INSTALL_PREFIX=/ ..

**Comment by RobertCElliott** [comment]
That workaround enables a successful build.

**Comment by kellycouch** [comment]
Fixed
