### ISSUE TITLE
[AEP] The ipmctl tool does not support Fatal Injection Error under Windows 2019 

### ISSUE THREAD

**Issue by AllenKivowitz** [intel/ipmctl#75]
A tester is reporting that with 512GB AEP(QS) in Memory Mode (100% volatile) and and 12 x 64gb 2U-rank RDIMMs in 2-2-2 configuration, the "ipmctl" tool (win) version:3374 executed under Windows 2019 produces a message: "Injecting a Fatal Media Error is unsupported on this OS. Please contact your OSV for assistance in performing this action." All other DSM Injections (e.g. Temperature, Spare Block, Unsafe Shutdown) works fine using the ipmctl tool. However, when using a different tool dsm tool on the same SUT with Windows 2019 the Fatal Error Injections works succesfully.
![dl360-w2k19-ipmctl-unsupportedfatal-inject 1](https://user-images.githubusercontent.com/46574886/51004337-c4a6ea00-14ff-11e9-8eca-7fe410166327.JPG)

**Comment by kellycouch** [comment]
ipmctl does not utilize standardized DSMs, such as Error Inject DSM. It only uses a proprietary PassThrough DSM path. Due to limitations in this path on MS Windows, Fatal Media Error injection is prohibited because it is not possible to recover using ipmctl.

**Comment by AllenKivowitz** [comment]
Sounds good.  I'll report back with this information.
