### ISSUE TITLE
Starting Specific Diagnostic Causes Segmentation Fault

### ISSUE THREAD

**Issue by patr-geary-smci** [intel/ipmctl#76]
If I specify a specific diagnostic to run on the mainline pull of ipmctl, it'll die.  Doesn't matter which diag, all of them segfault.

# ipmctl start -diagnostic -dimm 0x1101
*correct, proper output for each entry*
# ipmctl start -diagnostic Quick -dimm 0x1101
*Segmentation Fault*

Not sure how much of this stuff is staged by BIOS

Attached strace.

[strace-ipmctl_diagnostic_quick.log](https://github.com/intel/ipmctl/files/2751565/strace-ipmctl_diagnostic_quick.log)

**Comment by kellycouch** [comment]
Do other commands work? Are you able to enumerate any DCPMMs? This issue isn't present on our reference platform. 
For example:
`ipmctl show -dimm`

From log, it looks like a crash occurs just after reading SMBIOS tables. Maybe there is an entry missing from your BIOS that is expected?

Will you provide a diagnostic recording? Execute below and then attach the resulting PBR files.

`ipmctl show -dimm -record`
and
`ipmctl start -diagnostic -dimm 0x1101 -record`

**Comment by patr-geary-smci** [comment]
Additionally, I am using WW52 (5316?) firmware.


I haven't tried using a known good ipmctl that I validated against before; I just tried mainline everything for my test.


The other commands were functional.  I'll chuck you the record dumps on it probably Wednesday; kinda needed to use the system for other testing.

?

________________________________

**Comment by patr-geary-smci** [comment]
Looks like there was some weird mixture that was happening.

Did a fresh ipmctl build against the BIOS I was testing and it surprisingly worked, despite me actually believing I attempted this before.

No idea what was going on there, older ipmctl build was spitting out the segfaults, new one is not.

Closing.
