### ISSUE TITLE
ipmctl should use EFI_NVDIMM_LABEL_FLAGS_LOCAL label flag for local namespaces

### ISSUE THREAD

**Issue by LouisLaborde** [intel/ipmctl#77]
Windows 2019 SCM bus driver complains that the platform firmware is not compliant when it finds local namespaces with the label field missing EFI_NVDIMM_LABEL_FLAGS_LOCAL, as show below in the event logged:

The firmware on this computer is not fully compliant with the industry standards required for storage-class memory support. Storage-class memory devices on this computer may not work properly.
Local namespace with a single label does not have the local flag.

ipmctl should use that flag when creating namespaces in non-interleaved regions.

**Comment by kellycouch** [comment]
Can you share the full error message, including what’s in the “Details” tab? That will make it a lot easier to narrow down the error.

Also, is this a warning or a failure?

**Comment by kellycouch** [comment]
Thanks for your submission. After reviewing, I found that MS driver is being too strict and the spec allows for LOCAL flag to be optional as long as NLabels is 1. MS acknowledged this and is planning to fix it in a future release.

From UEFI Specification:
```
EFI_NVDIMM_LABEL_FLAGS_LOCAL – When set, the complete label set is local to a single
NVDIMM Label Storage Area. When clear, the complete label set is contained on multiple NVDIMM
Label Storage Areas. If NLabel is 1, then setting this flag is optional and it is implied that the
EFI_NVDIMM_LABEL_FLAGS_LOCAL flag is set, as the complete label set is local to a single
NVDIMM Label Storage Area


NLabel
Total number of labels describing this namespace. The NLabel field contains the number of labels
required to describe a namespace.

```

**Comment by kellycouch** [comment]
Louis - you filed this issue against ipmctl for OS, which does not support namespace manipulation (writing/reading). Can you further explain the context of using ipmctl to create a namespace?

**Comment by louislaborde** [comment]
I didn't realize that ipmctl for OS and ipmctl for EFI were 2 different projects, Sorry.
I would like ipmctl for EFI to set the flag EFI_NVDIMM_LABEL_FLAGS_LOCAL for local labels, Thanks.

**Comment by kellycouch** [comment]
Please see fix: https://github.com/intel/ipmctl/commit/bccc98aa337f86087a9ddfe1706bcebc41feefd0

**Comment by kellycouch** [comment]
Please confirm fix meets your request so we can close.
