### ISSUE TITLE
Use controller rather than core temperature

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#8]
For consistency, switch these to use "controller" rather than "core":

```
src/os/monitor/AcpiEventMonitor.h:#define ACPI_SMART_HEALTH_EVENT_TEMP_CORE_STR "core temp : "
DcpmemPkg/cli/ShowErrorCommand.h:#define ERROR_THERMAL_TYPE_CORE_STR     L"Core Temperature"

```
I don't see where it comes from, but this message also uses "core temperature threshold":
`The firmware consistency and settings check detected that DIMM 0x0011 is reporting a core temperature threshold of 104 C which is above the recommended threshold 102 C.
`

**Comment by juston-li** [comment]
Fixed in 479ba723aa6938d0a3da3bdcee1dc7a877fc8e85

Thanks!

**Comment by RobertCElliott** [comment]
I found that other string (and one more) not fixed in https://github.com/intel/ipmctl/commit/479ba723aa6938d0a3da3bdcee1dc7a877fc8e85

```
src/os/efi_shim/os_efi_hii_auto_gen_strings.h:L"The quick health check detected that DIMM %ls is reporting a core temperature of %d C which is above the alarm threshold %d C.", // STR_QUICK_CONTROLLER_TEMP_EXCEEDS_ALARM_THR = 214
src/os/efi_shim/os_efi_hii_auto_gen_strings.h:L"The firmware consistency and settings check detected that DIMM 0x%04x is reporting a core temperature threshold of %d C which is above the recommended threshold %d C.", // STR_FW_CORE_TEMPERATURE_THRESHOLD_ERROR = 259

```

**Comment by juston-li** [comment]
Hmm those are autogenerated files that should have been updated with my changes in 479ba72 to DcpmemPkg/driver/Core/Diagnostics/DiagnosticsMessages.uni.

Can you try deleting src/os/efi_shim/os_efi_hii_auto_gen_strings.h?
I'll check the dependencies in CMake, it might not be rebuilding it when DiagnosticsMessages.uni is modified.

**Comment by RobertCElliott** [comment]
A clean build fixed that, and touching the .uni file always triggered updated.  I've been copying trees between systems, which probably threw off some of the file dates.
