### ISSUE TITLE
Observing error while updating Firmware upgrade

### ISSUE THREAD

**Issue by ilavazhagu** [intel/ipmctl#81]
Hi,

Observing error while updating Firmware upgrade through ipmctl tool.

Load FW on DIMM 0x0001: Error (261) - An address range scrub operation is currently in progress
Load FW on DIMM 0x0011: Error (68) - A firmware image is already staged for execution. A power cycle is required before another can be staged.

Help us to resolve this fw update issue.

**Comment by gldiviney** [comment]
Yes, the kernel is doing this in Linux. It is outside the control of the IPMCTL software. The work-around is to retry until all dimms either show success or the "already staged" message. I generally do this with 15 second pauses between attempts.

**Comment by ilavazhagu** [comment]
I tried "ipmctl load -source xxx.bin -dimm" and observed Error (261) is randomly varying between the DIMM.

Load FW on DIMM 0x0001: Error (68) - A firmware image is already staged for execution. A power cycle is required before another can be staged.
Load FW on DIMM 0x0011: Error (68) - A firmware image is already staged for execution. A power cycle is required before another can be staged.
Load FW on DIMM 0x0101: Error (69) - Failed to validate and stage firmware image.
Load FW on DIMM 0x0111: Error (68) - A firmware image is already staged for execution. A power cycle is required before another can be staged.

**Comment by gldiviney** [comment]
There has been some work on this lately. Which release are you working from? I posted 3413 today and it may help you

**Comment by jb2780** [comment]
I'm seeing the same thing with ARS running at EFI Shell. Is it possible to add an option to command to force it to wait for pending ARS operations to complete? Or support something similar to (https://pmem.io/ndctl/ndctl-wait-scrub.html) to wait for pending ARS operations to complete?

I can apply the workaround mentioned (polling with 15 second waits), but it's not exactly straight-forward to poll on stdout, especially at EFI.

**Comment by kellycouch** [comment]
Upcoming release shall resolve this by actively cancelling any ARS in progress when attempting a FW Update. Documentation will be released that notes this change.

**Comment by kellycouch** [comment]
Auto-cancelling ARS in progress should be present in builds starting with 1.00.00.3440:

https://github.com/intel/ipmctl/releases/tag/v01.00.00.3440
