### ISSUE TITLE
Total memory capacity showing it as  inaccessible memory

### ISSUE THREAD

**Issue by ilavazhagu** [intel/ipmctl#82]
whenever moved from App-direct to memory mode, Total memory capacity showing it as inaccessible memory.
is there any known ipmctl tool issue?

**Comment by kellycouch** [comment]
There is a BIOS setting that determines 1LM or 2LM enabled. If set to 1LM only, then any memory configured for Memory Mode (2LM) will be inaccessible.

You can confirm by running:
`ipmctl show -system pcat `

And reviewing results of 
`CurrentMemoryMode: `

**Comment by ilavazhagu** [comment]
Out put of the "ipmctl show -system pcat "

Pls check and confirm whether it is in 1LM/2LM mode.

Type: 0x0
Length: 16 bytes
TypeEquals: PlatformCapabilityInfoTable
IntelNVDIMMManagementSWConfigInputSupport: 0x1
MemoryModeCapabilities: 0x27
CurrentMemoryMode: 0x14
PersistentMemoryRASCapability: 0x0

**Comment by kellycouch** [comment]
MemoryModeCapabilities: 0x27 indicates BIOS is 2LM is supported/enabled.
CurrentMemoryMode: 0x14 indicates 1LM is currently enabled, 2LM is not.

Can you provide output of 'show -topology' ? 

When populating DCPMM, it is required to have 1+ DDR4 on same iMC as any DCPMM, else 2LM is rejected.

**Comment by ilavazhagu** [comment]
Still observing same issue, below are logs.
 show topology

[root@localhost ~]# ipmctl show -topology

 DimmID | MemoryType                  | Capacity  | PhysicalID| DeviceLocator
==============================================================================
 0x0001 | Logical Non-Volatile Device | 252.4 GiB | 0x0032    | DIMM_A2
 0x0101 | Logical Non-Volatile Device | 252.4 GiB | 0x0038    | DIMM_D2
 0x1001 | Logical Non-Volatile Device | 252.4 GiB | 0x003e    | DIMM_G2
 0x1101 | Logical Non-Volatile Device | 252.4 GiB | 0x0044    | DIMM_K2
 N/A    | DDR4                        | 16.0 GiB  | 0x0031    | DIMM_A1
 N/A    | DDR4                        | 16.0 GiB  | 0x0033    | DIMM_B1
 N/A    | DDR4                        | 16.0 GiB  | 0x0035    | DIMM_C1
 N/A    | DDR4                        | 16.0 GiB  | 0x0037    | DIMM_D1
 N/A    | DDR4                        | 16.0 GiB  | 0x0039    | DIMM_E1
 N/A    | DDR4                        | 16.0 GiB  | 0x003b    | DIMM_F1
 N/A    | DDR4                        | 16.0 GiB  | 0x003d    | DIMM_G1
 N/A    | DDR4                        | 16.0 GiB  | 0x003f    | DIMM_H1
 N/A    | DDR4                        | 16.0 GiB  | 0x0041    | DIMM_J1
 N/A    | DDR4                        | 16.0 GiB  | 0x0043    | DIMM_K1
 N/A    | DDR4                        | 16.0 GiB  | 0x0045    | DIMM_L1
 N/A    | DDR4                        | 16.0 GiB  | 0x0047    | DIMM_M1
[root@localhost ~]#

now the current Memory mode is appearing it as 0x15

Type: 0x0
Length: 16 bytes
TypeEquals: PlatformCapabilityInfoTable
IntelNVDIMMManagementSWConfigInputSupport: 0x1
MemoryModeCapabilities: 0x27
CurrentMemoryMode: 0x15
PersistentMemoryRASCapability: 0x0

In accesscible state:

[root@localhost ~]# ipmctl show -memoryresources

Capacity=1009.8 GiB
MemoryCapacity=1008.0 GiB
AppDirectCapacity=0.0 GiB
UnconfiguredCapacity=0.0 GiB
InaccessibleCapacity=1.8 GiB
ReservedCapacity=0.0 GiB
[root@localhost ~]#

can you provide us the next step ?

**Comment by ilavazhagu** [comment]
some more clarification required, now the current mode 0x15.
can you clarify whether it is 1LM or 2 LM mode ? 

Type: 0x0
Length: 16 bytes
TypeEquals: PlatformCapabilityInfoTable
IntelNVDIMMManagementSWConfigInputSupport: 0x1
MemoryModeCapabilities: 0x27
CurrentMemoryMode: 0x15
PersistentMemoryRASCapability: 0x0

**Comment by kellycouch** [comment]
0x15 = Current MM=2LM,  Allowed MM=2LM.
Will plan to include bit decoding in future release...

**Comment by ilavazhagu** [comment]
Thanks for the clarification.

**Comment by kellycouch** [comment]
Great. OK to close?

**Comment by ilavazhagu** [comment]
let us know docs to refer this hexa decimal code. am observing different value with different system.

MemoryModeCapabilities: 0x6C728327
CurrentMemoryMode: 0x94

**Comment by kellycouch** [comment]
Hi. To get complete details, please consult your DCPMM supplier or Intel Support contact to request access to document# 554415 - Intel NVM DIMM Management Software-Firmware Interface Specification.
