### ISSUE TITLE
Report Speed in MT/s rather than MHz

### ISSUE THREAD

**Issue by RobertCElliott** [intel/ipmctl#85]
`ipmctl show -a -dimm` reports the DDR bus speed:
```
   DataWidth=64 b
   TotalWidth=72 b
    Speed=2666 MHz
```
The first D in DDR means data is transmitted on both the rising and falling clock edges, so:
- the clock frequency is 1333 MHz
- the data transfer rate is 2666 MT/s (megatransfers/second)

(i.e., 64 bits of data are transferred on each clock edge).

**Suggestion:**
Correct the units to:
  Speed=2666 MT/s

**Comment by kellycouch** [comment]
Thanks for the correction.
