### ISSUE TITLE
TEMP_FILE_PATH and LOG_INSTALL_PATH are not properly expanded on Windows

### ISSUE THREAD

**Issue by LouisLaborde** [intel/ipmctl#86]
The paths based on the following defines are not properly expanded:
#define LOG_INSTALL_PATH "%APPDATA%\\Intel\\ipmctl\\"
#define TEMP_FILE_PATH "%APPDATA%\\Intel\\ipmctl\\"

Running ipmctl.exe on Windows causes the creation of a local directory %APPDATA% which I don't think is the result expected. And this local directory is not simple to delete: I do it by unsetting the env variable APPDATA with "set APPDATA=" followed by issuing the command "rmdir /s /q %APPDATA%"

Instead, the 2 paths LOG_INSTALL_PATH and TEMP_FILE_PATH should be be expanded based on the environment variable %APPDATA%.

**Comment by gldiviney** [comment]
thanks - will examine

**Comment by gldiviney** [comment]
Louis - Can you check this behavior on the current master tip? Thanks

**Comment by kellycouch** [comment]
Fixed 3537+
