### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by kiendinh** [intel/ipmctl#90]
I got the following failure when trying to compile ipmctl. I'm using a Clear Linux (v28260) system. Default ipmctl doesn't work with the error "Error: There is not enough memory to complete the requested operation." so I needed to compile by myself.

cd /home/intel/workspace/ipmctl/output && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/intel/workspace/ipmctl /home/intel/workspace/ipmctl /home/intel/workspace/ipmctl/output /home/intel/workspace/ipmctl/output /home/intel/workspace/ipmctl/output/CMakeFiles/manpage.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/intel/workspace/ipmctl/output'
make -f CMakeFiles/manpage.dir/build.make CMakeFiles/manpage.dir/build
make[2]: Entering directory '/home/intel/workspace/ipmctl/output'
[ 74%] Generating man pages
/usr/bin/a2x -f manpage -a mansource=ipmctl -a manmanual="ipmctl" -a ipmctl_version=01.00.00.3279 -a os_build=1 -a manpage=1 -D /home/intel/workspace/ipmctl/output/release/manpage /home/intel/workspace/ipmctl/Documentation/ipmctl/ipmctl.txt
gzip -f /home/intel/workspace/ipmctl/output/release/manpage/ipmctl.1
[ 75%] Generating man pages
/usr/bin/a2x -f manpage -a mansource=ipmctl -a manmanual="ipmctl" -a ipmctl_version=01.00.00.3279 -a os_build=1 -a manpage=1 -D /home/intel/workspace/ipmctl/output/release/manpage /home/intel/workspace/ipmctl/Documentation/ipmctl/DIMM_Discovery/ipmctl-show-device.txt
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/intel/workspace/ipmctl/output/release/manpage/ipmctl-show-device.xml" returned non-zero exit status 4

make[2]: *** [CMakeFiles/manpage.dir/build.make:138: release/manpage/ipmctl-show-device.1.gz] Error 1
make[2]: Leaving directory '/home/intel/workspace/ipmctl/output'
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/manpage.dir/all] Error 2
make[1]: Leaving directory '/home/intel/workspace/ipmctl/output'
make: *** [Makefile:133: all] Error 2

**Comment by gldiviney** [comment]
Is this the complete output that you see? If not, can you attach the complete log file?

**Comment by kiendinh** [comment]
Hi @gldiviney Please find in the attachment the log files. By the way compiling with static options you mentioned in #39 also stops at the same error.

[cmake.log](https://github.com/intel/ipmctl/files/2961685/cmake.log)
[make.log](https://github.com/intel/ipmctl/files/2961689/make.log)

**Comment by gldiviney** [comment]
This is a side-effect of supporting multiple environments. We're looking at what would make the most sense for all going forward. Stay tuned.
