### ISSUE TITLE
Document nonstandard build requirements for `libsafec`

### ISSUE THREAD

**Issue by ahkok** [intel/ipmctl#91]
The `libsafec` library needs to be compiled with specific non-standard flags in order for `ipmctl` to be functional. This requirement needs to be documented and explained, and one should not have to find out from a closed bug report that this requirement exists.

Moreover, it should be explained why a nonstandard build option is needed, and why it is not a security risk to deviate from the standard compile options.

This issue can also be resolved by removing libsafec as a dependency entirely (not statically linking either, of course). That would be a better solution, since libsafec is of dubious benefit to the project.

**Comment by gldiviney** [comment]
This is a side-effect of supporting multiple environments. We're looking at what would make the most sense for all going forward. Stay tuned.

**Comment by ahkok** [comment]
Ideally, it would be to remove safelibc entirely based on the guidance from other linked discussion threads.

**Comment by kellycouch** [comment]
This is under investigation.
