### ISSUE TITLE
IPMCTL installation fail in RHEL 7.6 OS

### ISSUE THREAD

**Issue by Muthu2112** [intel/ipmctl#92]
Hi ,

I am trying to install IPMCTL tool in RHEL 7.6 OS and installed all dependencies. 

Steps Followed 
1.git clone https://github.com/intel/ipmctl
2.cmake -DCMAKE_INSTALL_PREFIX=/usr .. -DBUILDNUM=01.00.00.3440
3. make-j all

Facing following error while doing "make -j all" 

a2x: ERROR: "xmllint" --nonet --noout --valid "/root/ipmctl/ipmctl/output/debug/manpage/ipmctl-dump-goal.xml" returned non-zero exit status 4
make[2]: *** [debug/manpage/ipmctl-dump-goal.1.gz] Error 1
a2x: ERROR: "xmllint" --nonet --noout --valid "/root/ipmctl/ipmctl/output/debug/manpage/ipmctl-show-goal.xml" returned non-zero exit status 4
make[2]: *** [debug/manpage/ipmctl-show-goal.1.gz] Error 1
a2x: ERROR: "xmllint" --nonet --noout --valid "/root/ipmctl/ipmctl/output/debug/manpage/ipmctl-create-goal.xml" returned non-zero exit status 4
make[2]: *** [debug/manpage/ipmctl-create-goal.1.gz] Error 1
a2x: ERROR: "xmllint" --nonet --noout --valid "/root/ipmctl/ipmctl/output/debug/manpage/ipmctl-show-system-capabilities.xml" returned non-zero exit status 4
make[2]: *** [debug/manpage/ipmctl-show-system-capabilities.1.gz] Error 1
a2x: ERROR: "xmllint" --nonet --noout --valid "/root/ipmctl/ipmctl/output/debug/manpage/ipmctl-show-device.xml" returned non-zero exit status 4
make[2]: *** [debug/manpage/ipmctl-show-device.1.gz] Error 1
make[2]: Leaving directory `/root/ipmctl/ipmctl/output'
make[1]: *** [CMakeFiles/manpage.dir/all] Error 2
make[1]: Leaving directory `/root/ipmctl/ipmctl/output'
make: *** [all] Error 2

Any help

**Comment by gldiviney** [comment]
Have you installed the following? "asciidoctor, asciidoctor-pdf, asciidoc"

**Comment by Muthu2112** [comment]
Installed below except asciidoctor-pdf where it couldn't find in yum repo 

asciidoc-doc-8.6.8-5.el7.noarch
asciidoc-latex-8.6.8-5.el7.noarch
asciidoc-8.6.8-5.el7.noarch

However issue got resolved by executing below command
make -j all -i
make install -i

But want to know if any impact

**Comment by gldiviney** [comment]
Great, thanks!
