### ISSUE TITLE
No DIMM in the system (Intel P4500 installed)

### ISSUE THREAD

**Issue by amtrek** [intel/ipmctl#93]
Hi,
My system has intelP4500 SSD installed but while I perform ipmctl show --dimm, I get the response of  No DIMMs in the system.  I am trying to create a region using ipmctl and mount my SSD for my application

`No DIMMs in the system.`

Is there any setting that I need to turn on in order to access my persistent memory and allow ndctl to set create a large namespace over my ssd ?

**Comment by gldiviney** [comment]
This software was written to interact with the DCPMM product we make (i.e. https://itpeernetwork.intel.com/intel-optane-dc-persistent-memory-operating-modes/#gs.32wd1p). It will not interact with the SSD you've mentioned.

**Comment by amtrek** [comment]
Thanks gldiviney, I have learnt from other folks that I've mistaken the
concept of persistent with the Non-volatile memory express. It appears our
device is a block device.

**Comment by gldiviney** [comment]
Thanks for clarifying!
