### ISSUE TITLE
Adjust goal config capacities that would violate minimum 2LM NM:FM ratio

### ISSUE THREAD

**Issue by swiginton** [intel/ipmctl#95]
If the AppDirect granularity is allowed to be 1 GiB (instead of the default 32 GiB), it is possible to request a goal configuration that would result in a very poor (or even problematic) near memory to far memory ratio in 2LM mode.  Consider, for example, a goal configuration request on a socket in a 1-1-1 configuration that has a 4 x 16 GiB RDIMMs and 2 x 128 GiB DPCMMs.  If this request was made...
  ipmctl create -goal MemoryMode=1

...a goal config for 99% AppDirect (249 GiB) and 1% volatile memory (~2.5 GB) would be created.  Since the system will be in 2LM, this NM:FM ratio is well outside the recommended 1:4 to 1:16 ratio.

Could the API automatically adjust the percentage to at least satisfy the 1:2 NM:FM ratio, similar to how this is automatically done for CPU SKU limits?  In the above example, the API may adjust the MemoryMode percentage to 100% or fail the request altogether.

In the 1-1-1 example above, if the RDIMMs were 16 GiB and the DCPMMs were 512 GiB, then the same goal config request may be adjusted so that there is 13% volatile DCPMM capacity and 87% AppDirect.  This would keep the NM:FM ratio at least at 1:2.

**Comment by kellycouch** [comment]
Appreciate this feedback. This is something we have considered previously and your comment helps get the ball rolling.

**Comment by gldiviney** [comment]
Fixed - will be sync'd soon. Warning will now appear when limits are violated and the user has not used the 'force' option
