### ISSUE TITLE
Is SMBUS protocol ready to be used?

### ISSUE THREAD

**Issue by chowo12345** [intel/ipmctl#96]
I saw that there are code related to DDR-T and SMBUS protocol selection support in the latest codebase (v2.0).  Is SMBUS protocol ready to be used? or it is just a hook?  If it is ready, can it be used in OS or just UEFI?

Will be great to know more,

**Comment by kellycouch** [comment]
Hi,

Can you be more specific about the support you've found that is of interest and what use case you are specifically interested in?

**Comment by chowo12345** [comment]
Hi Kelly,

Thank you for your prompt response.

When we are running Citrix Xen Server 7.6 with DCPMM Memory Mode to take advantage of large memory capacity, DCPMM memory mode functions well.  However, there is a problem.  Since Xen Server hypervisor is not a full blown Linux OS, we cannot run ipmctl which is needed to do some basic monitoring.   The place we can run user space binary is Dom0 VM (privileged virtual machine with full expose of PCIe devices on the host).  Unfortunately, DDR-T access is not exposed by the hypervisor, ipmctl cannot show the sensor and health data of DCPMM DIMMs.  After reading thru the latest code, seems that SMBus support is available. Since SMBus controller of PCH is accessible in Dom0 VM, we think that this may be a possible way to run ipmctl.   

We have a few questions on SMBus support:
1. Is it ready to be used yet? Or it is just a "hook" for future implementation?
2. If it is ready, can it be used in OS ipmctl? or it is just for UEFI shell only?

Thank you.  

Regards,
Otto Chow 

Remark:  I work for Intel as well ... submit this as an issue because there may be other end customers with access to DCPMM having the same need.

**Comment by kellycouch** [comment]
ipmctl does not offer support for using PCH SMBus. There is some support enabled to access DIMM via CPU SPD SMBUS controller - this is only available from UEFI today. Work is under way to support this same CPU SPD SMBus controller access via Passthrough DSM, but if you cannot access existing passthrough from the VM, I expect you'll be blocked here as well.

It is possible to make modifications to the passthrough layer to access DIMMs directly via SMBus, *IF* your hardware provides this physical path. But we have no plans to add this support today - as every board layout is different.
