### ISSUE TITLE
Memory leak in nvm_get_number_of_memory_topology_devices()

### ISSUE THREAD

**Issue by iakovos-panourgias** [intel/ipmctl#97]
Hi, 

**Description:**
nvm_get_number_of_memory_topology_devices() leaks 62,976 bytes every time it is called.

**Steps to reproduce:**
Compile and run the attached test application using valgrind:
[nvm_get_number_of_memory_topology_devices_memory_leak.txt](https://github.com/intel/ipmctl/files/3165751/nvm_get_number_of_memory_topology_devices_memory_leak.txt)

gcc -Wall -g -o run_nvm_get_number_of_memory_topology_devices_memory_leak.exe nvm_get_number_of_memory_topology_devices_memory_leak.c -lipmctl
valgrind --leak-check=full run_nvm_get_number_of_memory_topology_devices_memory_leak.exe

**Expected results:**
 No memory leak(s).

**Actual results:** 
valgrind reports several memory leaks; including this one:
==158746== 62,976 bytes in 1 blocks are definitely lost in loss record 27 of 29
==158746==    at 0x4C2B9B5: calloc (vg_replace_malloc.c:711)
==158746==    by 0x4EC4A4B: GetSystemTopology (NvmDimmConfig.c:8576)
==158746==    by 0x4E6A0B2: nvm_get_number_of_memory_topology_devices (nvm_management.c:469)
==158746==    by 0x4007CC: main (nvm_get_number_of_memory_topology_devices_memory_leak.c:17)

**Version:**
01.00.00.3402

**Root cause:**
nvm_get_number_of_memory_topology_devices() creates a pointer (type TOPOLOGY_DIMM_INFO) and passes it to gNvmDimmDriverNvmDimmConfig.GetSystemTopology(). GetSystemTopology() allocates memory and returns it to nvm_get_number_of_memory_topology_devices(). nvm_get_number_of_memory_topology_devices() never frees the allocated memory and the user application has no way of freeing this memory once the library call returns.

**Solution:**
Before calling nvm_get_number_of_devices() (in file nvm_management.c:line 494); you should free the allocated memory. You can do this by adding the following line:
FREE_POOL_SAFE(pDimmTopology);

Kind regards,
Iakovos

**Comment by kellycouch** [comment]
Thanks for the detailed report! We'll plan to resolve in upcoming release.

**Comment by kellycouch** [comment]
Fixed here: https://github.com/intel/ipmctl/commit/ba1b14d904a72c2c60c45ae5e97c9b8dfc866e80
