### ISSUE TITLE
No effect after creating goal (App Direct mode)

### ISSUE THREAD

**Issue by davidliu2012** [intel/ipmctl#98]
My system has a Xeon Goal Cascade Lake CPU and 2x 128GB DCPMM DIMMs (and 4x 32GB DDR4 RDIMMs). After running "#ipmctl create -goal PersistentMemoryType=AppDirect", it shows the goal is successfully set and asks me to restart. However, after restart there is no change to the memory configuration. I am still running in Memory mode. The command "#ipmctl show –goal" still returns the pending goal. I wonder if that is an issue with the tool or my hardware platform has problems? Thanks!

**Comment by gldiviney** [comment]
Did you perform a power-cycle restart or just a warm restart? If not a power cycle, please try that.

**Comment by davidliu2012** [comment]
Thanks for answering! I tried both. I have disconnected the power supply and then power it back on.  But still no change to the memory configuration.

**Comment by gldiviney** [comment]
Ok - which OS are you in when you set up the goal?

**Comment by davidliu2012** [comment]
I have tried a couple of Linux distributions: 16.04 (kernel 4.15), 18.04 (kernel 4.19) and 19.04 (kernel 5.00).  I had the exact same problem on these OS versions.

**Comment by gldiviney** [comment]
If you have access to the UEFI shell, can you try it there?

**Comment by davidliu2012** [comment]
I also tried. Same problem.  I have tested on different motherboards. With Asus Z11PA-U12, there is no effect after creating the goal. With Supermicro X11SPL-F, DCPMM channels cannot be recognized after setting the goal. However, DCPMM works well in memory mode in these different platforms. I wonder if that is a software issue, a firmware issue or hardware is incompatible.

**Comment by gldiviney** [comment]
I certainly could be. Can you tell me which versions of BIOS/FW/SW you have?

**Comment by kellycouch** [comment]
Please also attach the output of this command:
`ipmctl show -dimm -pcd`

**Comment by davidliu2012** [comment]
Thanks for replying. Unfortunately, I have just returned the platform. The motherboard vendor suggested that my motherboard is incompatible and needs HW revision. I will let you know if changing the motherboard can fix my issue.

**Comment by gldiviney** [comment]
Thanks - please let us know what you discover

**Comment by kellycouch** [comment]
Closing. Reopen as needed.
